### PR TITLE
Fix the lazy listing of builtin property names

### LINKED ISSUE #3606: Assertion ecma_object_check_class_name_is_object (obj_p) in ecma_object_get_class_name
###### JerryScript revision
72f8ef34

###### Build platform
Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
String(JSON.stringify(Array.prototype[Symbol.unscopables]))
```

###### Output
```text
ICE: Assertion 'ecma_object_check_class_name_is_object (obj_p)' failed at jerryscript/jerry-core/ecma/operations/ecma-objects.c(ecma_object_get_class_name):2600.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657de1c in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5662e9d8 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#5  0x5662ea19 in jerry_assert_fail (assertion=0x566fda80 "ecma_object_check_class_name_is_object (obj_p)", file=0x566fcd40 "jerryscript/jerry-core/ecma/operations/ecma-objects.c", function=0x566c3e00 <__func__.7039.lto_priv.640> "ecma_object_get_class_name", line=2600) at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#6  0x5665ceff in ecma_object_get_class_name (obj_p=0xf5f01660) at jerryscript/jerry-core/ecma/operations/ecma-objects.c:2600
#7  0x5666f4e9 in ecma_builtin_json_serialize_property (context_p=0xffffc2f0, holder_p=0xf5d001b0, key_p=0xd) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.c:1171
#8  0x5666fae6 in ecma_builtin_json_str_helper (context_p=0xffffc2f0, arg1=4126152291) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.c:1313
#9  0x56670abc in ecma_builtin_json_stringify (this_arg=4126152195, arg1=4126152291, arg2=72, arg3=72) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.c:1556
#10 0x5666b667 in ecma_builtin_json_dispatch_routine (builtin_routine_id=83, this_arg_value=4126152195, arguments_list=0xffffc3d0, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.inc.h:34
#11 0x566739f7 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_JSON, builtin_routine_id=83, this_arg_value=4126152195, arguments_list_p=0xffffc3d0, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1049
#12 0x56673c58 in ecma_builtin_dispatch_call (obj_p=0xf5f015d0, this_arg_value=4126152195, arguments_list_p=0xffffc6cc, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1074
#13 0x5664c7ff in ecma_op_function_call_simple (func_obj_p=0xf5f015d0, this_arg_value=4126152195, arguments_list_p=0xffffc6cc, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:985
#14 0x5664d101 in ecma_op_function_call (func_obj_p=0xf5f015d0, this_arg_value=4126152195, arguments_list_p=0xffffc6cc, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1206
#15 0x5660fa30 in opfunc_call.lto_priv.465 (frame_ctx_p=0xffffc690) at jerryscript/jerry-core/vm/vm.c:746
#16 0x565d962d in vm_execute (frame_ctx_p=0xffffc690) at jerryscript/jerry-core/vm/vm.c:4262
#17 0x565d9ba5 in vm_run (bytecode_header_p=0xf4f03c00, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4364
#18 0x5660e1ec in vm_run_global (bytecode_p=0xf4f03c00) at jerryscript/jerry-core/vm/vm.c:320
#19 0x5669120a in jerry_run (func_val=4126148595) at jerryscript/jerry-core/api/jerry.c:594
#20 0x5668d80c in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:748
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3606.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/ecma-builtins.c [hunk 1]
```diff
@@ -995,7 +995,18 @@ ecma_builtin_list_lazy_property_names (ecma_object_t *object_p, /**< a built-in
...
+#if ENABLED (JERRY_ES2015)
+        if (curr_property_p->attributes & ECMA_PROPERTY_FLAG_ENUMERABLE)
+        {
+          ecma_collection_push_back (main_collection_p, name);
+        }
+        else
+        {
+#endif /* ENABLED (JERRY_ES2015) */
+          ecma_collection_push_back (for_non_enumerable_p, name);
+#if ENABLED (JERRY_ES2015)
```
Comment (galpeter) [inline jerry-core/ecma/builtin-objects/ecma-builtins.c]: It would be good to find a way to avoid the guards for closing brackets. What if we do this? 
```c
#if ENABLED(...)
  if (...)
  {
    ...
  }
else
#endif
  {
    ..
  }
```

Still not an ideal one, but at least we have removed the need for the second #ifdef guard.
@dbatyai  What do you think?

Comment (dbatyai) [reply jerry-core/ecma/builtin-objects/ecma-builtins.c]: +1

Comment (rerobika) [reply jerry-core/ecma/builtin-objects/ecma-builtins.c]: Good idea! I've updated the PR.
