### PR TITLE
Fix surrogate pair lookahead in String.prototype.toUpper

### LINKED ISSUE #4013: heap-buffer-overflow in lit_read_code_unit_from_utf8
###### JerryScript revision
dfd9d44

###### Build platform
Ubuntu 16.04.6 LTS (Linux 4.15.0-99-generic x86_64)

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
 --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
 --compile-flag=-fno-common --compile-flag=-g --strip=off \
 --system-allocator=on --logging=on --linker-flag=-fuse-ld=gold \
 --error-messages=on --profile=es2015-subset --lto=off 
```

###### Test case
```
var a = "\ud800".toUpperCase();
```

###### Output
```
=================================================================
==18731==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf600071f at pc 0x080c4e9c bp 0xffd56088 sp 0xffd56078
READ of size 1 at 0xf600071f thread T0
    #0 0x80c4e9b in lit_read_code_unit_from_utf8 /home/jerryscript/jerry-core/lit/lit-strings.c:431
    #1 0x80c5457 in lit_cesu8_peek_next /home/jerryscript/jerry-core/lit/lit-strings.c:522
    #2 0x8137d08 in ecma_builtin_string_prototype_object_conversion_helper /home/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c:1005
    #3 0x8138a9a in ecma_builtin_string_prototype_dispatch_routine /home/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c:1360
    #4 0x8081845 in ecma_builtin_dispatch_routine /home/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1214
    #5 0x80819eb in ecma_builtin_dispatch_call /home/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1238
    #6 0x8097f0e in ecma_op_function_call_simple /home/jerryscript/jerry-core/ecma/operations/ecma-function-object.c:844
    #7 0x8098d15 in ecma_op_function_call /home/jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1141
    #8 0x80f965c in opfunc_call /home/jerryscript/jerry-core/vm/vm.c:778
    #9 0x810c3fa in vm_execute /home/jerryscript/jerry-core/vm/vm.c:4690
    #10 0x810c93e in vm_run /home/jerryscript/jerry-core/vm/vm.c:4792
    #11 0x80f7e64 in vm_run_global /home/jerryscript/jerry-core/vm/vm.c:339
    #12 0x804def4 in jerry_run /home/jerryscript/jerry-core/api/jerry.c:579
    #13 0x804acbf in main /home/jerryscript/jerry-main/main-unix.c:759
    #14 0xf77c5646 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18646)
    #15 0x8048fb0  (/home/jerryscript/build/bin/jerry+0x8048fb0)

0xf600071f is located 0 bytes to the right of 15-byte region [0xf6000710,0xf600071f)
allocated by thread T0 here:
    #0 0xf79fadee in malloc (/usr/lib32/libasan.so.2+0x96dee)
    #1 0x80c0a22 in jmem_heap_alloc /home/jerryscript/jerry-core/jmem/jmem-heap.c:254
    #2 0x80c0af2 in jmem_heap_gc_and_alloc_block /home/jerryscript/jerry-core/jmem/jmem-heap.c:289
    #3 0x80c0b71 in jmem_heap_alloc_block /home/jerryscript/jerry-core/jmem/jmem-heap.c:323
    #4 0x810ca7d in ecma_alloc_string_buffer /home/jerryscript/jerry-core/ecma/base/ecma-alloc.c:194
    #5 0x80621f8 in ecma_new_ecma_string_from_utf8_buffer /home/jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:269
    #6 0x80621f8 in ecma_new_ecma_string_from_utf8 /home/jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:353
    #7 0x807456c in ecma_find_or_create_literal_string /home/jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:134
    #8 0x80c6e8d in parser_compute_indicies /home/jerryscript/jerry-core/parser/js/js-parser.c:146
    #9 0x80c8db6 in parser_post_processing /home/jerryscript/jerry-core/parser/js/js-parser.c:1040
    #10 0x80ce773 in parser_parse_source /home/jerryscript/jerry-core/parser/js/js-parser.c:2282
    #11 0x80d1ab0 in parser_parse_script /home/jerryscript/jerry-core/parser/js/js-parser.c:2896
    #12 0x804db7c in jerry_parse /home/jerryscript/jerry-core/api/jerry.c:441
    #13 0x804ac76 in main /home/jerryscript/jerry-main/main-unix.c:750
    #14 0xf77c5646 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18646)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/jerryscript/jerry-core/lit/lit-strings.c:431 lit_read_code_unit_from_utf8
Shadow bytes around the buggy address:
  0x3ec00090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000d0: fa fa fa fa fa fa fa fa fa fa 00 04 fa fa 00 05
=>0x3ec000e0: fa fa 00[07]fa fa fd fa fa fa fd fa fa fa fd fd
  0x3ec000f0: fa fa 00 00 fa fa 00 00 fa fa 00 06 fa fa 00 00
  0x3ec00100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec00110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec00120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec00130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==18731==ABORTING

```

Credits: This vulnerability is detected by chong from OWL337.

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #4013.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c [hunk 1]
```diff
@@ -1004,11 +1004,15 @@ ecma_builtin_string_prototype_object_conversion_helper (ecma_string_t *input_str
 #if ENABLED (JERRY_ESNEXT)
     if (lit_is_code_point_utf16_high_surrogate (cp))
     {
-      const ecma_char_t next_ch = lit_cesu8_peek_next (input_curr_p);
-      if (lit_is_code_point_utf16_low_surrogate (next_ch))
+      if (input_curr_p < input_str_end_p)
```
Comment (dbatyai) [inline jerry-core/ecma/builtin-objects/ecma-builtin-string-prototype.c:1007]: This condition could be merged with the outer one.

**Comment by rerobika** [comment]
Thanks for the reviews I've updated the PR.
