### PR TITLE
Fix allocation problems when using import and export

### LINKED ISSUE #2908: Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed in jmem_heap_allocated_size
###### Jerry version:

```
Checked revision: 351acdf5

Build command: ./tools/build.py --clean --debug --logging=on --error-messages=on --profile=es2015-subset
```

###### OS:

```
Linux-4.15.0-51-generic-x86_64-with-Ubuntu-18.04-bionic
```

###### Test case:

```javascript
import{p0hc"=
```

###### Backtrace:

```text
import{p0hc"=
~~~~~~~~~~~^
Script Error: SyntaxError: Unterminated string literal. [line: 1, column: 12]
ICE: Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed at  jerryscript/jerry-core/jmem/jmem-heap.c(jmem_heap_finalize):143.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7dc7535 in __GI_abort () at abort.c:79
#2  0x00005555555cf284 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at  jerryscript/jerry-port/default/default-fatal.c:71
#3  0x000055555558f984 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at  jerryscript/jerry-core/jrt/jrt-fatals.c:58
#4  0x000055555558f9d6 in jerry_assert_fail (assertion=0x5555555df198 "JERRY_CONTEXT (jmem_heap_allocated_size) == 0", 
    file=0x5555555df118 " jerryscript/jerry-core/jmem/jmem-heap.c", 
    function=0x5555555ead20 <__func__.4822> "jmem_heap_finalize", line=143)
    at  jerryscript/jerry-core/jrt/jrt-fatals.c:82
#5  0x000055555558ef77 in jmem_heap_finalize () at  jerryscript/jerry-core/jmem/jmem-heap.c:143
#6  0x000055555558ebef in jmem_finalize () at  jerryscript/jerry-core/jmem/jmem-allocator.c:170
#7  0x000055555555b7f5 in jerry_cleanup () at  jerryscript/jerry-core/api/jerry.c:231
#8  0x000055555555ab89 in main (argc=3, argv=0x7fffffffddc8) at  jerryscript/jerry-main/main-unix.c:940
```

<sup>Found by [libFuzzer](https://llvm.org/docs/LibFuzzer.html). </sup>

### PR DESCRIPTION
**Pull request by szilagyiadam**
Construct ecma_string only when there is no parser error using lit_object's index in parser_module_parse_export_caluse and parser_module_parse_import_clause
Fixes #2908

Co-authored-by: Tibor Dusnoki tdusnoki@inf.u-szeged.hu
JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser-module.c [hunk 1]
```diff
@@ -342,20 +339,28 @@ parser_module_parse_export_clause (parser_context_t *context_p) /**< parser cont
...
-                                                      context_p->lit_object.literal_p->prop.length);
+      export_name_index = context_p->lit_object.index;
 
       lexer_next_token (context_p);
     }
 
+    lexer_literal_t *literal_p = PARSER_GET_LITERAL (local_name_index);
+    local_name_p = ecma_new_ecma_string_from_utf8 (literal_p->u.char_p, literal_p->prop.length);
+    ecma_ref_ecma_string (local_name_p);
+    export_name_p = local_name_p;
```
Comment (dbatyai) [inline jerry-core/parser/js/js-parser-module.c]: These last two lines could be moved into an `else` block after the condition below, so we don't ref/deref unnecessarily

File: jerry-core/parser/js/js-parser-module.c [hunk 2]
```diff
@@ -427,19 +430,28 @@ parser_module_parse_import_clause (parser_context_t *context_p) /**< parser cont
...
-                                                     context_p->lit_object.literal_p->prop.length);
+      import_name_index = context_p->lit_object.index;
+      
       lexer_next_token (context_p);
     }
 
+    lexer_literal_t *literal_p = PARSER_GET_LITERAL (local_name_index);
+    local_name_p = ecma_new_ecma_string_from_utf8 (literal_p->u.char_p, literal_p->prop.length);
+    ecma_ref_ecma_string (local_name_p);
+    import_name_p = local_name_p;
```
Comment (dbatyai) [inline jerry-core/parser/js/js-parser-module.c]: Same here.

File: jerry-core/parser/js/js-parser-module.c [hunk 3]
```diff
@@ -342,20 +339,31 @@ parser_module_parse_export_clause (parser_context_t *context_p) /**< parser cont
...
+    {
+      lexer_literal_t *as_literal_p = PARSER_GET_LITERAL (export_name_index);
+      export_name_p = ecma_new_ecma_string_from_utf8 (as_literal_p->u.char_p, as_literal_p->prop.length);
+    }
+    else
+    {
+      ecma_ref_ecma_string (local_name_p);
+    }
+    
+
```
Comment (rerobika) [inline jerry-core/parser/js/js-parser-module.c]: One new line is enough.

File: jerry-core/parser/js/js-parser-module.c [hunk 4]
```diff
@@ -427,19 +433,31 @@ parser_module_parse_import_clause (parser_context_t *context_p) /**< parser cont
...
+    {
+      lexer_literal_t *as_literal_p = PARSER_GET_LITERAL (import_name_index);
+      local_name_p = ecma_new_ecma_string_from_utf8 (as_literal_p->u.char_p, as_literal_p->prop.length);
+    }
+    else
+    {
+      ecma_ref_ecma_string (local_name_p);
+    }
+    
+
```
Comment (rerobika) [inline jerry-core/parser/js/js-parser-module.c]: ditto.

File: jerry-core/parser/js/js-parser-module.c [hunk 5]
```diff
@@ -413,10 +420,8 @@ parser_module_parse_import_clause (parser_context_t *context_p) /**< parser cont
 
     lexer_construct_literal_object (context_p, &context_p->token.lit_location, LEXER_IDENT_LITERAL);
 
-    local_name_p = ecma_new_ecma_string_from_utf8 (context_p->lit_object.literal_p->u.char_p,
-                                                   context_p->lit_object.literal_p->prop.length);
-    ecma_ref_ecma_string (local_name_p);
-    import_name_p = local_name_p;
+    uint16_t local_name_index = context_p->lit_object.index;
+    uint16_t import_name_index = PARSER_MAXIMUM_NUMBER_OF_LITERALS;
```
Comment (dbatyai) [inline jerry-core/parser/js/js-parser-module.c]: The naming is mixed up here a bit, it should be the opposite of the export case. We have an import name first, and an optional local name later. Please switch these up.

File: jerry-core/parser/js/js-parser-module.c [hunk 6]
```diff
@@ -427,19 +432,30 @@ parser_module_parse_import_clause (parser_context_t *context_p) /**< parser cont
...
-        ecma_deref_ecma_string (import_name_p);
         parser_raise_error (context_p, PARSER_ERR_IDENTIFIER_EXPECTED);
       }
 
       lexer_construct_literal_object (context_p, &context_p->token.lit_location, LEXER_IDENT_LITERAL);
 
-      ecma_deref_ecma_string (local_name_p);
-      local_name_p = ecma_new_ecma_string_from_utf8 (context_p->lit_object.literal_p->u.char_p,
-                                                     context_p->lit_object.literal_p->prop.length);
+      import_name_index = context_p->lit_object.index;
```
Comment (dbatyai) [inline jerry-core/parser/js/js-parser-module.c]: Here you should assign the local name.

File: jerry-core/parser/js/js-parser-module.c [hunk 7]
```diff
@@ -427,19 +432,30 @@ parser_module_parse_import_clause (parser_context_t *context_p) /**< parser cont
...
+
       lexer_next_token (context_p);
     }
 
+    lexer_literal_t *literal_p = PARSER_GET_LITERAL (local_name_index);
+    local_name_p = ecma_new_ecma_string_from_utf8 (literal_p->u.char_p, literal_p->prop.length);
```
Comment (dbatyai) [inline jerry-core/parser/js/js-parser-module.c]: This should be the import name string.

File: jerry-core/parser/js/js-parser-module.c [hunk 8]
```diff
@@ -427,19 +432,30 @@ parser_module_parse_import_clause (parser_context_t *context_p) /**< parser cont
...
+    import_name_p = local_name_p;
+
+    if (import_name_index != PARSER_MAXIMUM_NUMBER_OF_LITERALS)
```
Comment (dbatyai) [inline jerry-core/parser/js/js-parser-module.c]: And here you should check if we have a local name index.

File: jerry-core/parser/js/js-parser-module.c [hunk 9]
```diff
@@ -427,19 +432,30 @@ parser_module_parse_import_clause (parser_context_t *context_p) /**< parser cont
...
+    {
+      lexer_literal_t *as_literal_p = PARSER_GET_LITERAL (import_name_index);
+      local_name_p = ecma_new_ecma_string_from_utf8 (as_literal_p->u.char_p, as_literal_p->prop.length);
+    }
+    else
+    {
```
Comment (dbatyai) [inline jerry-core/parser/js/js-parser-module.c]: Please also move the `local_name_p = import_name_p;` assignment into this block, similarly to the export case.

**Comment by szilagyiadam** [comment]
Did the requested changes.
