### PR TITLE
CBC_PUSH_THIS_LITERAL must be converted back to CBC_PUSH_THIS during emitting unary lvalue opcode

### LINKED ISSUE #2937: Expression c++ is not recognized correctly
### Testcase:
````
1. var foo = function () {
2. 	var c = 0;
3. 	var p1 = this[c];
4. 	print(p1);
5. 	var p2 = this[c++];
6. 	print(p2);
7. };
8. foo();
````
### Command:
````
./jerryscript/build/bin/jerry testcase.js
````
### Result:
````
undefined
Exception backtrace:
  0: 20190612/373821.js:5
  1: 20190612/373821.js:9
Script Error: ReferenceError: Undefined reference.
````
### Comment:
Both variable p1 and variable p2 should be `undefined`, but jerry throws an exception on line 5. Other more, other engines do not throw exception on line 5, such as v8, spiderMonkey, chakra, javascriptCore.

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2937.

Co-authored-by: Gabor Loki loki@inf.u-szeged.hu
JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: tests/jerry/regression-test-issue-2937.js [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+assert (c === 0);
+
+var p3 = this[++c];
+assert (p3 === undefined);
+assert (c === 1);
+
+var p4 = this[--c];
+assert (p4 === undefined);
+assert (c === 0);
+
```
Comment (dbatyai) [inline tests/jerry/regression-test-issue-2937.js]: Please remove this trailing empty line.

Comment (rerobika) [reply tests/jerry/regression-test-issue-2937.js]: Thanks, I didn't notice that.
