### PR TITLE
Fix memory leak in ecma_op_abstract_relational_compare

### LINKED ISSUE #4234: Memory leak in ecma_op_abstract_relational_compare
###### JerryScript revision
3b7409f3a7311430bb4e5e1f065e386b0db71d9a
(latest master - 2020.09.24.)

###### Build platform
Ubuntu 18.04.5 LTS (Linux 4.15.0-112-generic x86_64)

###### Build steps
./tools/build.py --clean --debug --logging=on --error-messages=on

###### Test cases
1 < Symbol(1)
Symbol(1) < 1
1n < Symbol(1)
Symbol(1) < 1n

##### Output
```
ICE: Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed at /home/oszi/jerryscript/jerry-core/jmem/jmem-heap.c(jmem_heap_finalize):107.

ICE: Assertion 'ECMA_EXTENDED_PRIMITIVE_IS_REF_EQUALS_TO_ONE (bigint_p)' failed at /home/oszi/jerryscript/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_bigint_list):132.
```
###### Expected behavior
no mem leak

The bug is in ecma_op_abstract_relational_compare. There are many early returns when calling ecma_op_to_number to Symbol.
In these cases allocated objects should be freed. Fix is coming.

### PR DESCRIPTION
**Pull request by ossy-szeged**
Fixes #4234.

JerryScript-DCO-1.0-Signed-off-by: Csaba Osztrogonác csaba.osztrogonac@h-lab.eu

### CODE REVIEW

File: jerry-core/ecma/operations/ecma-comparison.c [hunk 1]
```diff
@@ -393,11 +393,15 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
...
       {
+        ecma_free_value (prim_second_converted_value);
+        ecma_free_value (prim_first_converted_value);
         return ECMA_VALUE_ERROR;
       }
 
       if (ECMA_IS_VALUE_ERROR (ecma_op_to_number (py, &ny)))
       {
+        ecma_free_value (prim_second_converted_value);
+        ecma_free_value (prim_first_converted_value);
```
Comment (zherczeg) [inline jerry-core/ecma/operations/ecma-comparison.c:404]: What about setting ret_value to ECMA_VALUE_ERROR and jump to the end.
Maybe
```
ret_value = ECMA_IS_VALUE_ERROR (ecma_op_to_number (px, &nx));
if (ECMA_IS_VALUE_ERROR (ret_value))
{
  goto error;
}
```

**Review by zherczeg — CHANGES_REQUESTED** [review]

File: jerry-core/ecma/operations/ecma-comparison.c (hunk 1 above)
Comment (ossy-szeged) [reply jerry-core/ecma/operations/ecma-comparison.c:404]: In my opinion we should avoid goto whenever possible. In this case we can do easily, I can't see a reason to prefer the "evil" goto here.

Comment (dbatyai) [reply jerry-core/ecma/operations/ecma-comparison.c:404]: One reason would be code size.

Comment (ossy-szeged) [reply jerry-core/ecma/operations/ecma-comparison.c:404]: I checked, this change increases .text size with 16 bytes. Are you guys sure the ugly goto solution would decrease the code size significantly?

Comment (rerobika) [reply jerry-core/ecma/operations/ecma-comparison.c:404]: +1 for the goto solution, also, the checks can be merged:

```c
if (ECMA_IS_VALUE_ERROR (ecma_op_to_number (px, &nx)) || ECMA_IS_VALUE_ERROR (ecma_op_to_number (py, &ny)))
{
  goto error;
}
```

Comment (dbatyai) [reply jerry-core/ecma/operations/ecma-comparison.c:404]: There's nothing ugly about using goto, we're using it all over the code base already, it works very well for cleaning up values after an error happens. It keeps the code tidy by not having to duplicate cleanup code after each error check, and if done correctly makes the code more readable.

I think this fear of using gotos is completely unwarranted. Of course you should not throw them around haphazardly, but when used correctly they can be very efficient.

Comment (ossy-szeged) [reply jerry-core/ecma/operations/ecma-comparison.c:404]: I can't understand your admiration for goto and I still think it is ugly and should be avoided whenever possible. But you are the reviewers not me, so I understanded I have to add gotos to the code to be able to fix this memory leak, I'll update the PR.

Just a note, with goto solution, the code size will be exactly same as the current size. The merged ifs didn't change anything, the compiler already merged them, but I agree it makes the code cleaner, so I merged them.

File: jerry-core/ecma/operations/ecma-comparison.c [hunk 2]
```diff
@@ -391,14 +391,11 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
...
+      if (ECMA_IS_VALUE_ERROR (ecma_op_to_number (px, &nx))
+          || ECMA_IS_VALUE_ERROR (ecma_op_to_number (py, &ny)))
       {
-        return ECMA_VALUE_ERROR;
-      }
-
-      if (ECMA_IS_VALUE_ERROR (ecma_op_to_number (py, &ny)))
-      {
-        return ECMA_VALUE_ERROR;
+        ret_value = ECMA_VALUE_ERROR;
```
Comment (rerobika) [inline jerry-core/ecma/operations/ecma-comparison.c:397]: This assignment would be no longer needed if `ret_value` would be initialized to `ECMA_VALUE_ERROR` at the variable declaration.

Comment (ossy-szeged) [reply jerry-core/ecma/operations/ecma-comparison.c:397]: I'm not 100% sure if it will be correct. There is a ret_value == ECMA_VALUE_EMPTY later in the code.
I can't see at first sight if it expects the init empty value or an empty value from a later assignment.

**Review by zherczeg — APPROVED** [review]
LGTM

File: jerry-core/ecma/operations/ecma-comparison.c (hunk 2 above)
Comment (ossy-szeged) [reply jerry-core/ecma/operations/ecma-comparison.c:397]: I checked your idea, it is definitely wrong and would cause assertion on tests/jerry/es.next/bigint4.js test:
ICE: Assertion 'jcontext_has_pending_exception ()' failed at /home/oszi/jerryscript/jerry-core/vm/vm.c(vm_loop):4556.
Error: ERR_FAILED_INTERNAL_ASSERTION

Comment (rerobika) [reply jerry-core/ecma/operations/ecma-comparison.c:397]: This idea is definitely **NOT** wrong only some bigint comparison adjustment was required.

```diff
diff --git a/jerry-core/ecma/operations/ecma-comparison.c b/jerry-core/ecma/operations/ecma-comparison.c
index 988bca810..8bd0f198c 100644
--- a/jerry-core/ecma/operations/ecma-comparison.c
+++ b/jerry-core/ecma/operations/ecma-comparison.c
@@ -355,7 +355,6 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
                                      ecma_value_t y, /**< second operand */
                                      bool left_first) /**< 'LeftFirst' flag */
 {
-  ecma_value_t ret_value = ECMA_VALUE_EMPTY;
 
   /* 1., 2. */
   ecma_value_t prim_first_converted_value = ecma_op_to_primitive (x, ECMA_PREFERRED_TYPE_NUMBER);
@@ -376,6 +375,7 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
 
   const bool is_px_string = ecma_is_value_string (px);
   const bool is_py_string = ecma_is_value_string (py);
+  ecma_value_t ret_value = ECMA_VALUE_ERROR;
 
   if (!(is_px_string && is_py_string))
   {
@@ -394,7 +394,6 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
       if (ECMA_IS_VALUE_ERROR (ecma_op_to_number (px, &nx))
           || ECMA_IS_VALUE_ERROR (ecma_op_to_number (py, &ny)))
       {
-        ret_value = ECMA_VALUE_ERROR;
         goto end;
       }
 
@@ -498,12 +497,12 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
           if (ret_value == ECMA_VALUE_FALSE)
           {
             ret_value = ECMA_VALUE_UNDEFINED;
+            goto end;
           }
           else
           {
             compare_result = ecma_bigint_compare_to_bigint (px, ret_value);
             ecma_free_value (ret_value);
-            ret_value = ECMA_VALUE_EMPTY;
           }
         }
       }
@@ -512,13 +511,13 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
         ecma_number_t ny;
         if (ECMA_IS_VALUE_ERROR (ecma_op_to_number (py, &ny)))
         {
-          ret_value = ECMA_VALUE_ERROR;
           goto end;
         }
 
         if (ecma_number_is_nan (ny))
         {
           ret_value = ECMA_VALUE_UNDEFINED;
+          goto end;
         }
         else
         {
@@ -526,15 +525,12 @@ ecma_op_abstract_relational_compare (ecma_value_t x, /**< first operand */
         }
       }
 
-      if (ret_value == ECMA_VALUE_EMPTY)
+      if (invert_result)
       {
-        if (invert_result)
-        {
-          compare_result = -compare_result;
-        }
-
-        ret_value = ecma_make_boolean_value (compare_result < 0);
+        compare_result = -compare_result;
       }
+
+      ret_value = ecma_make_boolean_value (compare_result < 0);
     }
 #endif /* ENABLED (JERRY_BUILTIN_BIGINT) */
   }

```

Comment (ossy-szeged) [reply jerry-core/ecma/operations/ecma-comparison.c:397]: Of course, it can be done with refactoring unrelated codes. But please keep in mind that the goal of this PR is ONLY to fix a memory leak, not to reach make ecma_op_abstract_relational_compare smallest code size. I support you to make it more optimal, but please do it in a follow-up PR.

**Review by rerobika — APPROVED** [review]
LGTM

File: jerry-core/ecma/operations/ecma-comparison.c (hunk 2 above)
Comment (rerobika) [reply jerry-core/ecma/operations/ecma-comparison.c:397]: Conclusion: Since this change is not related to the PR, I'm waiting for the follow-up patch.
