### PR TITLE
Raw string length should be adjusted when UTF8 string is converted to CESU8

### LINKED ISSUE #3812: Assertion destination_p == destination_start_p + literal_p->length in lexer_convert_literal_to_chars
#### JerryScript revision
3b4c2592

#### Build platform
Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic

#### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset \

```

#### Test case
```js
$={[$$`𞹴`
```

#### Backtrace
```text
#4  0x56686cf6 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript//jerry-port/default/default-fatal.c:30
#5  0x565dda51 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript//jerry-core/jrt/jrt-fatals.c:63
#6  jerry_assert_fail (assertion=0x566cd6a0 "destination_p == destination_start_p + literal_p->length", file=0x566cce40 "jerryscript//jerry-core/parser/js/js-lexer.c", function=0x566ce6a0 <__func__.6675> "lexer_convert_literal_to_chars", line=2327) at jerryscript//jerry-core/jrt/jrt-fatals.c:87
#7  0x56654a33 in lexer_convert_literal_to_chars (context_p=<optimized out>, literal_p=<optimized out>, local_byte_array_p=<optimized out>, opts=<optimized out>) at jerryscript//jerry-core/parser/js/js-lexer.c:2327
#8  0x5667bf73 in parser_tagged_template_literal_append_strings (context_p=<optimized out>, template_obj_p=<optimized out>, raw_strings_p=<optimized out>, prop_idx=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-tagged-template-literal.c:74
#9  0x5665d972 in parser_parse_tagged_template_literal (context_p=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-expr.c:1514
#10 parser_process_unary_expression (grouping_level=0, context_p=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-expr.c:2146
#11 parser_parse_expression (context_p=<optimized out>, options=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-expr.c:3486
#12 0x566583f0 in lexer_expect_object_literal_id (context_p=0xffffc680, ident_opts=1) at jerryscript//jerry-core/parser/js/js-lexer.c:3042
#13 0x5665f8ed in parser_parse_object_literal (context_p=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-expr.c:930
#14 parser_parse_unary_expression (grouping_level_p=<optimized out>, context_p=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-expr.c:1829
#15 parser_parse_expression (context_p=<optimized out>, options=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-expr.c:3477
#16 0x56666514 in parser_parse_block_expression (context_p=0xffffc680, options=0) at jerryscript//jerry-core/parser/js/js-parser-expr.c:3425
#17 0x5667665c in parser_parse_statements (context_p=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser-statm.c:3154
#18 0x565eb68b in parser_parse_source (arg_list_p=arg_list_p@entry=0x0, arg_list_size=arg_list_size@entry=0, source_p=source_p@entry=0x5670c600 <buffer> "varo={[void[]^this`\\`\\`𞹴`()]:this!==function(){}^[,]+[,]++};Array.prototype.pop.call(o);", source_size=<optimized out>, parse_opts=<optimized out>, error_location_p=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser.c:2177
#19 0x565eccf6 in parser_parse_script (arg_list_p=<optimized out>, arg_list_size=<optimized out>, source_p=<optimized out>, source_size=<optimized out>, parse_opts=<optimized out>, bytecode_data_p=<optimized out>) at jerryscript//jerry-core/parser/js/js-parser.c:2808
#20 0x56577f9d in jerry_parse (resource_name_p=<optimized out>, resource_name_length=<optimized out>, source_p=<optimized out>, source_size=<optimized out>, parse_opts=<optimized out>) at jerryscript//jerry-core/api/jerry.c:447
#21 0x56570abf in main (argc=<optimized out>, argv=<optimized out>) at jerryscript//jerry-main/main-unix.c:750
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3812.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-lexer.c [hunk 1]
```diff
@@ -1135,6 +1135,9 @@ lexer_parse_string (parser_context_t *context_p, /**< context */
       length += 2 * 3;
       has_escape = true;
       source_p += 4;
+#if ENABLED (JERRY_ES2015)
+      raw_length_dec -= 2;
```
Comment (zherczeg) [inline jerry-core/parser/js/js-lexer.c:1139]: I don't think this can be < 0, so why change it to int32?

Comment (rerobika) [reply jerry-core/parser/js/js-lexer.c:1139]: I can be. in the related testcase  `raw_length_dec` - 2.

File: jerry-core/parser/js/js-lexer.c [hunk 2]
```diff
@@ -915,7 +915,7 @@ lexer_parse_string (parser_context_t *context_p, /**< context */
                     lexer_string_options_t opts) /**< options */
 {
 #if ENABLED (JERRY_ES2015)
-  size_t raw_length_dec = 0;
+  int32_t raw_length_dec = 0;
```
Comment (zherczeg) [inline jerry-core/parser/js/js-lexer.c:918]: What about calling this raw_length_adjusment, raw_length_diff, or raw_length_change?

Comment (rerobika) [reply jerry-core/parser/js/js-lexer.c]: Sure! I've updated the pr.
