### PR TITLE
Fix class literal scan

### LINKED ISSUE #4892: Assertion 'context_p->scope_stack_size == PARSER_MAXIMUM_DEPTH_OF_SCOPE_STACK' failed at jerry-core/parser/js/js-parser-expr.c(parser_parse_class):1160
## JerryScript commit hash
55acdf2048b390d0f56f12e64dbfb2559f0e70ad

## Build platform
Ubuntu 20.04 LTS

## Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --line-info=ON \
--stack-limit=10
```

## poc
```
function foo(a, i) {
    a[i] = 1;
    return a[i];
}
class MyArray extends class C extends Array {

} {

}
;
o = new MyArray();
print(foo);
print(1, foo(o, 0));
print(1, foo(o, 1));
o.__proto__.__proto__ = new Int32Array(2);
print(undefined, foo(o, 2));
print(undefined, foo(o, 2));
```

## assert log

```
ICE: Assertion 'context_p->scope_stack_size == PARSER_MAXIMUM_DEPTH_OF_SCOPE_STACK' failed at /home/sakura/jerryscript/jerry-core/parser/js/js-parser-expr.c(parser_parse_class):1160.
Error: ERR_FAILED_INTERNAL_ASSERTION

```

### PR DESCRIPTION
**Pull request by batizdaniel**
This patch fixes #4892

JerryScript-DCO-1.0-Signed-off-by: Daniel Batiz daniel.batiz@h-lab.eu

### CODE REVIEW

File: jerry-core/parser/js/js-scanner-util.c [hunk 1]
```diff
@@ -1748,17 +1748,14 @@ scanner_push_class_declaration (parser_context_t *context_p, /**< context */
 
   if (class_has_name)
   {
-    if (stack_mode == SCAN_STACK_CLASS_STATEMENT)
+    if (stack_mode == SCAN_STACK_CLASS_STATEMENT || stack_mode == SCAN_STACK_CLASS_EXPRESSION)
```
Comment (rerobika) [inline jerry-core/parser/js/js-scanner-util.c:1751]: This if can be removed

**Review by rerobika — CHANGES_REQUESTED** [review]

**Review by rerobika — APPROVED** [review]
LGTM

**Review by dbatyai — APPROVED** [review]
