### PR TITLE
Fix incorrect assertion in parser_parse_for_statement_start

### LINKED ISSUE #3655: Assertion literal_index < PARSER_REGISTER_START || !has_context in parser_parse_for_statement_start
###### JerryScript revision
3c7a776c

###### Build platform
Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
for (let i of id_36())

function testcase() {
    testcase
```

###### Output
```text
ICE: Assertion 'literal_index < PARSER_REGISTER_START || !has_context' failed at jerryscript/jerry-core/parser/js/js-parser-statm.c(parser_parse_for_statement_start):1317.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
(gdb) bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b43d in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5662e775 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#5  0x5662e7b6 in jerry_assert_fail (assertion=0x566e9f00 "literal_index < PARSER_REGISTER_START || !has_context", 
    file=0x566e93a0 "jerryscript/jerry-core/parser/js/js-parser-statm.c", function=0x566d8fc0 <__func__.5874.lto_priv.28> "parser_parse_for_statement_start", line=1317)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#6  0x565a323a in parser_parse_for_statement_start (context_p=0xffffcaf0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:1317
#7  0x565aa6ea in parser_parse_statements (context_p=0xffffcaf0) at jerryscript/jerry-core/parser/js/js-parser-statm.c:2812
#8  0x5663ce3f in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x567436c0 <buffer.lto_priv> "for (let i of id_36())\n\nfunction testcase() {\n    testcase\n", source_size=59, 
    parse_opts=0, error_location_p=0xffffcd20) at jerryscript/jerry-core/parser/js/js-parser.c:2096
#9  0x56640347 in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x567436c0 <buffer.lto_priv> "for (let i of id_36())\n\nfunction testcase() {\n    testcase\n", source_size=59, 
    parse_opts=0, bytecode_data_p=0xffffcde0) at jerryscript/jerry-core/parser/js/js-parser.c:2605
#10 0x56690c81 in jerry_parse (resource_name_p=0xffffd391 "test.js", resource_name_length=7, source_p=0x567436c0 <buffer.lto_priv> "for (let i of id_36())\n\nfunction testcase() {\n    testcase\n", 
    source_size=59, parse_opts=0) at jerryscript/jerry-core/api/jerry.c:448
#11 0x5668d887 in main (argc=2, argv=0xffffd1d4) at jerryscript/jerry-main/main-unix.c:744
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3655.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/base/ecma-globals.h [hunk 1]
```diff
@@ -121,6 +121,14 @@ typedef enum
   ECMA_PARSE_GENERATOR_FUNCTION = (1u << 8), /**< generator function is parsed */
 
   /* These flags are internally used by the parser. */
+#ifndef JERRY_NDEBUG
+  ECMA_PARSE_INTERNAL_FOR_IN_OFF_CONTEXT_ERROR = (1u << 9), /**< This flag is enabled when the for in/off statement
```
Comment (zherczeg) [inline jerry-core/ecma/base/ecma-globals.h:125]: Maybe shorter:
This flag represents an error in for in/of statements, which cannot be set if the parsing is completed successfully.

You can put the description before the declaration, or put the it before the flag is set in js-parser-statm.c.

**Comment by zherczeg** [comment]
Test case is missing.

File: jerry-core/ecma/base/ecma-globals.h (hunk 1 above)
Comment (rerobika) [reply jerry-core/ecma/base/ecma-globals.h]: Thanks, updated.
