### PR TITLE
Fix error handling in scanner in case of OOM

### LINKED ISSUE #3786: NULL dereference in scanner_reverse_info_list
###### JerryScript revision
https://github.com/jerryscript-project/jerryscript/commit/6cd309b5252d15f3e3e6481c72a4d8fa7f9557a9

###### Build platform
Ubuntu 20.04 LTS (Linux 5.4.0-31-generic x86_64)

###### Build steps

```sh
python tools/build.py --profile=es2015-subset --lto=off --compile-flag=-g \
--error-messages=on --debug --compile-flag=-g --strip=off --logging=on \
 --compile-flag=-fsanitize=address --stack-limit=15
```

###### Test case

```
function main() {
var v2 = new Float64Array(63797);
var v4 = "d".constructor;
var v6 = [1337,1337,1337,1337];
var v7 = [];
var v8 = {constructor:v6,a:v7};
var v9 = v8.a;
var v12 = 0;
v9.toString = v4;
var v14 = new Int16Array();
do {
    function v16(v17,v18,v19) {
        'use strict'
        var v20 = Int16Array.toLocaleString();
        var v22 = eval(v20);
    }
    var v24 = new Promise(v16);
    var v25 = v12 + 1;
    v12 = v25;
    v7[v25] = v14;
} while (v12 < 1337);
}
main();
```

###### Output

```
$ build/bin/jerry test.js
AddressSanitizer:DEADLYSIGNAL
=================================================================
==434582==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000010 (pc 0x55af4dd3f2b0 bp 0x7ffc7e016ab0 sp 0x7ffc7e016a80 T0)
==434582==The signal is caused by a READ memory access.
==434582==Hint: address points to the zero page.
    #0 0x55af4dd3f2af in scanner_reverse_info_list /tmp/jerryscript/jerry-core/parser/js/js-scanner-util.c:1557
    #1 0x55af4dd5150a in scanner_scan_all /tmp/jerryscript/jerry-core/parser/js/js-scanner.c:3217
    #2 0x55af4dd34f5e in parser_parse_source /tmp/jerryscript/jerry-core/parser/js/js-parser.c:2084
    #3 0x55af4dd38d76 in parser_parse_script /tmp/jerryscript/jerry-core/parser/js/js-parser.c:2697
..
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /tmp/jerryscript/jerry-core/parser/js/js-scanner-util.c:1557 in scanner_reverse_info_list
==434582==ABORTING
```

```
$ gdb -q -nx build/bin/jerry -ex 'r test.js'

Program received signal SIGSEGV, Segmentation fault.
0x00005555556422b0 in scanner_reverse_info_list (context_p=0x7fffffffca20) at /tmp/jerryscript/jerry-core/parser/js/js-scanner-util.c:1557
1557	  if (scanner_info_p->type == SCANNER_TYPE_END)
(gdb) x/i $rip
=> 0x5555556422b0 <scanner_reverse_info_list+133>:	movzbl 0x10(%rax),%eax
(gdb) i r rax
rax            0x0                 0
```

### LINKED ISSUE #3788: Assertion 'context_p->error == PARSER_ERR_NO_ERROR' failed at jerry-core/parser/js/js-scanner.c(scanner_scan_all):3196
###### JerryScript revision
https://github.com/jerryscript-project/jerryscript/commit/6cd309b5252d15f3e3e6481c72a4d8fa7f9557a9

###### Build platform
Ubuntu 20.04 LTS (Linux 5.4.0-31-generic x86_64)

###### Build steps

```sh
python tools/build.py --profile=es2015-subset --lto=off --compile-flag=-g \
--error-messages=on --debug --compile-flag=-g --strip=off --logging=on \
 --compile-flag=-fsanitize=address --stack-limit=15
```

###### Test case

```
function main() {
var v2 = [13.37,13.37];
var v4 = [1337,1337,1337];
var v5 = [parseFloat,parseFloat,v2];
var v8 = new Float64Array(63797);
var v10 = "d".constructor;
var v12 = [1337,1337,1337,1337];
var v13 = [];
var v14 = {constructor:v12,a:v13};
var v15 = v14.a;
var v18 = 0;
v15.toString = v10;
var v20 = new Int16Array();
do {
    var v25 = String.fromCharCode(1337,128);
    try {
        var v26 = eval(v25);
    } catch(v27) {
    }
    var v28 = v18 + 1;
    v18 = v28;
    v13[v28] = v20;
} while (v18 < 1337);
}
main();
```

###### Output

```
$ build/bin/jerry test.js
ICE: Assertion 'context_p->error == PARSER_ERR_NO_ERROR' failed at /tmp/jerryscript/jerry-core/parser/js/js-scanner.c(scanner_scan_all):3196.
Error: ERR_FAILED_INTERNAL_ASSERTION
Aborted (core dumped)
```

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3786 and fixes #3788.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-scanner.c [hunk 1]
```diff
@@ -3214,6 +3214,14 @@ scanner_scan_all (parser_context_t *context_p, /**< context */
   PARSER_TRY_END
```
Comment (zherczeg) [inline jerry-core/parser/js/js-scanner.c:3214]: Thewre is a code above:
```
#if ENABLED (JERRY_ES2015)
    context_p->status_flags &= (uint32_t) ~PARSER_IS_GENERATOR_FUNCTION;
#endif /* ENABLED (JERRY_ES2015) */
```
Looks unnecessary.

File: jerry-core/parser/js/js-scanner.c [hunk 2]
```diff
@@ -3193,7 +3193,7 @@ scanner_scan_all (parser_context_t *context_p, /**< context */
     }
     PARSER_CATCH
     {
-      JERRY_ASSERT (context_p->error == PARSER_ERR_NO_ERROR);
+      JERRY_ASSERT (context_p->error == PARSER_ERR_NO_ERROR || context_p->error == PARSER_ERR_OUT_OF_MEMORY);
```
Comment (zherczeg) [inline jerry-core/parser/js/js-scanner.c:3196]: the `PARSER_TRY (context_p->try_buffer)` could be enclosed in `if (context_p->error != PARSER_ERR_OUT_OF_MEMORY)`

File: jerry-core/parser/js/js-scanner.c [hunk 3]
```diff
@@ -3214,6 +3214,14 @@ scanner_scan_all (parser_context_t *context_p, /**< context */
   PARSER_TRY_END
 
   context_p->status_flags = scanner_context.context_status_flags;
+
+  if (JERRY_UNLIKELY (context_p->error == PARSER_ERR_OUT_OF_MEMORY))
+  {
+    parser_stack_free (context_p);
+    scanner_cleanup (context_p);
```
Comment (zherczeg) [inline jerry-core/parser/js/js-scanner.c:3221]: `scanner_cleanup` might be already called by `scanner_malloc`.

File: jerry-core/parser/js/js-scanner.c (hunk 1 above)
Comment (rerobika) [reply jerry-core/parser/js/js-scanner.c:3214]: Looks but this removal not corresponds to the fix.

File: jerry-core/parser/js/js-scanner.c (hunk 2 above)
Comment (rerobika) [reply jerry-core/parser/js/js-scanner.c:3196]: This is not a proper fix since in the internal try  block `scanner_pop_literal_pool` may allocates memory which could lead to OOM error.

**Comment by rerobika** [comment]
The patch is updated. The related testcases in the issues cannot be added since there is no way to ensure that the OOM happens in the scanner not elsewhere in the engine.

File: jerry-core/parser/js/js-scanner.c [hunk 4]
```diff
@@ -3193,17 +3197,16 @@ scanner_scan_all (parser_context_t *context_p, /**< context */
...
-        scanner_context.active_literal_pool_p = literal_pool_p->prev_p;
-
-        parser_list_free (&literal_pool_p->literal_pool);
-        scanner_free (literal_pool_p, sizeof (scanner_literal_pool_t));
+      if (JERRY_UNLIKELY (context_p->error == PARSER_ERR_OUT_OF_MEMORY))
+      {
+        parser_stack_free (context_p);
+        return;
       }
+
```
Comment (zherczeg) [inline jerry-core/parser/js/js-scanner.c:3209]: No need this newline.

File: jerry-core/parser/js/js-scanner-util.c [hunk 5]
```diff
@@ -463,6 +463,23 @@ scanner_literal_is_arguments (lexer_lit_location_t *literal_p) /**< literal */
   return lexer_compare_identifier_to_string (literal_p, (const uint8_t *) "arguments", 9);
 } /* scanner_literal_is_arguments */
 
+/**
+ * Release the active literal pool
+ */
+void
+scanner_release_active_literal_pool (scanner_context_t *scanner_context_p) /**< scanner context */
```
Comment (zherczeg) [inline jerry-core/parser/js/js-scanner-util.c:470]: `scanner_release_all_literal_pools`

**Comment by rerobika** [comment]
@zherczeg Thanks for the review, the PR is updated.

File: jerry-core/parser/js/js-scanner.c [hunk 6]
```diff
@@ -3193,16 +3197,14 @@ scanner_scan_all (parser_context_t *context_p, /**< context */
     }
     PARSER_CATCH
     {
-      JERRY_ASSERT (context_p->error == PARSER_ERR_NO_ERROR);
-
-      while (scanner_context.active_literal_pool_p != NULL)
-      {
-        scanner_literal_pool_t *literal_pool_p = scanner_context.active_literal_pool_p;
+      JERRY_ASSERT (context_p->error == PARSER_ERR_NO_ERROR || context_p->error == PARSER_ERR_OUT_OF_MEMORY);
```
Comment (zherczeg) [inline jerry-core/parser/js/js-scanner.c:3200]: I realized something. Iff we are inside the catch, how can this be `PARSER_ERR_NO_ERROR`?

**Comment by zherczeg** [comment]
I have been thinking about an alternative for this patch, which does not require a separate free function. 

It would look like this:
```
PARSER_CATCH
{
  while (scanner_context.active_binding_list_p != NULL) ...

  if (JERRY_LIKELY (context_p->error != PARSER_ERR_OUT_OF_MEMORY))
  {
    context_p->error = PARSER_ERR_NO_ERROR;

    PARSER_TRY (context_p->try_buffer)
    {
      ...
    }
    PARSER_CATCH
    {
      JERRY_ASSERT (context_p->error == PARSER_ERR_OUT_OF_MEMORY);
    }
  }

  JERRY_ASSERT (context_p->error == PARSER_ERR_NO_ERROR || context_p->error == PARSER_ERR_OUT_OF_MEMORY);

  if (JERRY_UNLIKELY (context_p->error == PARSER_ERR_OUT_OF_MEMORY))
  {
      release...
      parser_stack_free (context_p);
      return;
  }
}
```

What do you think? I can do it in a separate patch if you wish.

**Comment by rerobika** [comment]
+1 for the separate patch!

File: jerry-core/parser/js/js-scanner.c (hunk 6 above)
Comment (rerobika) [reply jerry-core/parser/js/js-scanner.c]: True, this case cannot happen.

**Comment by rerobika** [comment]
@zherczeg I've updated the PR with the suggested code above.
