### PR TITLE
Fix Typedarray.slice fastpath when the content type is matching

### LINKED ISSUE #4888: Assertion 'new_typedarray_info.offset == 0' failed at jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c(ecma_builtin_typedarray_prototype_slice):1631.
## JerryScript commit hash
55acdf2048b390d0f56f12e64dbfb2559f0e70ad

## Build platform
Ubuntu 20.04 LTS

## Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --line-info=ON \
--stack-limit=10
```

## poc
```
var ab = new Int8Array(20).map((v, i) => i).buffer;
var ta = new Int8Array(ab, 0, 10);
var seen_length = -1;
ta.constructor = {
    [Symbol.species]: function (len) {
        seen_length = len;
        return new Int8Array(ab, 1, len);
    }
};
print(-1, seen_length);
print([
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9
], ta);
var tb = ta.slice();
print(10, seen_length);
print([
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
], ta);
print([
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
], tb);
```

## assert log
```
ICE: Assertion 'new_typedarray_info.offset == 0' failed at /home/sakura/jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c(ecma_builtin_typedarray_prototype_slice):1631.

```

### PR DESCRIPTION
**Pull request by gergocs**
This patch fixes #4888.

The implementation is based on PR #4898, only resolved the conflicts and
applied requested changes.

Co-authored-by: Robert Fancsik robert.fancsik@h-lab.eu
JerryScript-DCO-1.0-Signed-off-by: Gergo Csizi gergocs@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c [hunk 1]
```diff
@@ -1711,14 +1711,35 @@ ecma_builtin_typedarray_prototype_slice (ecma_value_t this_arg, /**< this argume
...
+    if (JERRY_LIKELY (new_typedarray_info.offset == 0))
+    {
+      if (info_p->array_buffer_p == new_typedarray_info.array_buffer_p)
+      {
+        return new_typedarray;
+      }
+
+      memcpy (dst_buffer_p, src_buffer_p, count << info_p->shift);
+    }
+    else if (count >= new_typedarray_info.offset)
```
Comment (LaszloLango) [inline jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:1729]: Just to be fair, there was a comment on the original PR which has not been answered yet. I paste it here.

> What if count is less than the target offset? I don't think this condition is correct.
> 
> ```
> var buf = new ArrayBuffer(10);
> var a1 = new Int8Array(buf, 0, 5);
> a1.fill(1);
> a1.constructor = {
>     [Symbol.species]: function (len) {
>         return new Int8Array(buf, 5, 5);
>     }
> };
> var a2 = a1.slice(2,4);
> res = new Int8Array(buf, 0, 10);
> ```
> 
> Also, I don't think checking the offset is the right way, we need to check whether the two typedarrays use the same arraybuffer instead, and only then fall back to copying element-by-element.

_Originally posted by @dbatyai in https://github.com/jerryscript-project/jerryscript/pull/4898#discussion_r766609489_

Comment (gergocs) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:1729]: I checked the example and it worked just fine.

Comment (LaszloLango) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:1729]: Great, thanks.

**Review by LaszloLango — APPROVED** [review]
LGTM

**Review by robertsipka — CHANGES_REQUESTED** [review]
I have concerns about the results. The test case linked by Dániel run without an error message, but the result is correct? Sadly, no, please check it, use the mentioned test case in the PR as well, and make a results validation for `res` in the last line. Dániel's review seems appropriate to me.

**Review by robertsipka — APPROVED** [review]
LGTM

**Review by LaszloLango — APPROVED** [review]
still LGTM
