### PR TITLE
Uncontrolled memory allocation in jerry_port_read_source function

### LINKED ISSUE #4251: Uncontrolled memory allocation in jerry_port_read_source function
An uncontrolled memory allocation issue was discovered in jerry_port_read_source function in the default-module.c file.

###### JerryScript revision
4b2dbd5c2165f60e770e400d56c90d23fa224048
(latest master - 2020.09.30.)

###### Build platform
Ubuntu 16.04.1 (Linux 4.15.0-117-generic x86_64)

###### Build steps
```sh
python ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --lto=off --error-message=on --system-allocator=on 
```
###### Test case
any directory, e.g. a directory name "input"

###### Execution steps
```sh
./jerry input
```
###### Output
```sh
==78885==ERROR: AddressSanitizer failed to allocate 0x80002000 (-2147475456) bytes of LargeMmapAllocator (errno: 12)
==78885==Process memory map follows:
	0x08048000-0x08219000	/home/lily/Desktop/debugger/jerryscript/build/bin/jerry
	0x08219000-0x0821a000	/home/lily/Desktop/debugger/jerryscript/build/bin/jerry
	0x0821a000-0x08237000	/home/lily/Desktop/debugger/jerryscript/build/bin/jerry
	0x08237000-0x08238000	
	0x1ffff000-0x24000000	
	0x24000000-0x28000000	
	0x28000000-0x40000000	
	0xf5c00000-0xf5d00000	
	0xf5e00000-0xf5f00000	
	0xf6000000-0xf6100000	
	0xf6200000-0xf6300000	
	0xf6400000-0xf6500000	
	0xf65ad000-0xf776f000	
	0xf776f000-0xf778a000	/usr/lib32/libgcc_s.so.1
	0xf778a000-0xf778b000	/usr/lib32/libgcc_s.so.1
	0xf778b000-0xf778c000	/usr/lib32/libgcc_s.so.1
	0xf778c000-0xf77df000	/lib32/libm-2.23.so
	0xf77df000-0xf77e0000	/lib32/libm-2.23.so
	0xf77e0000-0xf77e1000	/lib32/libm-2.23.so
	0xf77e1000-0xf77e2000	
```

###### Expected behavior
Please check whether an input is a directory or a file. When the input is a directory, jerry_port_get_file_size function will return the file_size 0xffffffff. Or, add a limitation check before malloc in jerry_port_read_source function.

### PR DESCRIPTION
**Pull request by ossy-szeged**
jerry_port_read_source should exit with error message
if its parameter is a directory and not a regular file.

Fixes #4251.

JerryScript-DCO-1.0-Signed-off-by: Csaba Osztrogonác csaba.osztrogonac@h-lab.eu

### CODE REVIEW

**Review by rerobika — APPROVED** [review]
LGTM

File: jerry-port/default/default-module.c [hunk 1]
```diff
@@ -20,10 +20,15 @@
 #include <stdarg.h>
 #include <stdlib.h>
 #include <string.h>
+#include <sys/stat.h>
```
Comment (zherczeg) [inline jerry-port/default/default-module.c:23]: Is this win32 compatible?

Comment (ossy-szeged) [reply jerry-port/default/default-module.c:23]: Yes, it is. Windows has sys/stat.h, but no S_ISDIR macro, that's why we should define it.

**Review by zherczeg — APPROVED** [review]
LGTM
