### PR TITLE
Fix class extends value

### LINKED ISSUE #2658: Assertion 'type == ECMA_OBJECT_TYPE_EXTERNAL_FUNCTION' failed in ecma_op_function_construct
###### Jerry version:

```
Checked revision: ec142f5f
Build command: ./tools/build.py --clean --debug --profile=es2015-subset --logging=on
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
var A = class extends null {}
new A;
```

###### Backtrace:

```
ICE: Assertion 'type == ECMA_OBJECT_TYPE_EXTERNAL_FUNCTION' failed at jerryscript/jerry-core/ecma/operations/ecma-function-object.c(ecma_op_function_construct):1054.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a24801 in __GI_abort () at abort.c:79
#2  0x000055555555f2f6 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#3  0x000055555558b684 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#4  0x000055555558b6d6 in jerry_assert_fail (assertion=0x5555555e1970 "type == ECMA_OBJECT_TYPE_EXTERNAL_FUNCTION", 
    file=0x5555555e1338 "jerryscript/jerry-core/ecma/operations/ecma-function-object.c", function=0x5555555d2e90 <__func__.4934.lto_priv.539> "ecma_op_function_construct", line=1054)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#5  0x00005555555a0e55 in ecma_op_function_construct (func_obj_p=0x5555558f7498 <jerry_global_heap+216>, this_arg_value=291, arguments_list_p=0x7fffffffdbb4, arguments_list_len=0)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1054
#6  0x00005555555a0e22 in ecma_op_function_construct (func_obj_p=0x5555558f74a8 <jerry_global_heap+232>, this_arg_value=291, arguments_list_p=0x7fffffffdbb4, arguments_list_len=0)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1045
#7  0x000055555559602f in opfunc_construct (frame_ctx_p=0x7fffffffdbf0) at jerryscript/jerry-core/vm/vm.c:610
#8  0x000055555559bd43 in vm_execute (frame_ctx_p=0x7fffffffdbf0, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3446
#9  0x000055555559bfd7 in vm_run (bytecode_header_p=0x5555558f75c0 <jerry_global_heap+512>, this_binding_value=27, lex_env_p=0x5555558f73f0 <jerry_global_heap+48>, parse_opts=0, arg_list_p=0x0, 
    arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3531
#10 0x00005555555958f6 in vm_run_global (bytecode_p=0x5555558f75c0 <jerry_global_heap+512>) at jerryscript/jerry-core/vm/vm.c:227
#11 0x00005555555c2595 in jerry_run (func_val=203) at jerryscript/jerry-core/api/jerry.c:544
#12 0x00005555555c0ea0 in main (argc=3, argv=0x7fffffffe028) at jerryscript/jerry-main/main-unix.c:676
```

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2658 and ensures that when a class extends value is null and the class has no explicit constructor
the proper error is raised during constructing a class instance.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/operations/ecma-function-object.c [hunk 1]
```diff
@@ -1048,6 +1048,16 @@ ecma_op_function_construct (ecma_object_t *func_obj_p, /**< Function object */
...
+    case ECMA_OBJECT_TYPE_GENERAL:
+    {
+      /* Catch the special case when a the class extends value in null
+         and the class has no explicit constructor to raise TypeError.*/
+      JERRY_ASSERT (!ecma_op_function_has_construct_flag (arguments_list_p));
+      JERRY_ASSERT (ecma_get_object_prototype (func_obj_p) == NULL);
+
+      ret_value = ecma_raise_type_error (ECMA_ERR_MSG ("Super constructor null is not a constructor."));
+      break;
+    }
```
Comment (zherczeg) [inline jerry-core/ecma/operations/ecma-function-object.c]: Can it be moved to the `if (ext_func_obj_p->u.external_handler_cb == ecma_op_function_implicit_constructor_handler_cb)` below?

Comment (rerobika) [reply jerry-core/ecma/operations/ecma-function-object.c]: I'd rather not move it. The `ecma_op_function_implicit_constructor_handler_cb` check requires that the object's type must be `ECMA_OBJECT_TYPE_EXTERNAL_FUNCTION`, but for the special behavior for `class extends null {}` the class extends values's type is always `ECMA_OBJECT_TYPE_GENERAL`. See the related part [here](https://github.com/pando-project/jerryscript/blob/master/jerry-core/vm/vm.c#L1331).
