### PR TITLE
Fix iterator step calculation for bracketed property expressions

### LINKED ISSUE #3665: Assertion ecma_is_value_object (iterator) in ecma_op_iterator_next
###### JerryScript revision
28f2772

###### Build platform
Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
(function() {
    [Date[ReferenceError][String]] = []
})(function() {})

(function() {})(
    function() {
        [...{}]
    }
)
```

###### Output
```text
ICE: Assertion 'ecma_is_value_object (iterator)' failed at jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c(ecma_op_iterator_next):246.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
(gdb) bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b557 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5662eaa4 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#5  0x5662eae5 in jerry_assert_fail (assertion=0x566fe840 "ecma_is_value_object (iterator)", file=0x566fe5e0 "jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c", 
    function=0x566c6cc0 <__func__.6467.lto_priv.675> "ecma_op_iterator_next", line=246) at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#6  0x5664c505 in ecma_op_iterator_next (iterator=72, value=8) at jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c:246
#7  0x5664cb3a in ecma_op_iterator_step (iterator=72) at jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c:509
#8  0x5661707a in vm_loop.lto_priv.458 (frame_ctx_p=0xffffcac0) at jerryscript/jerry-core/vm/vm.c:1801
#9  0x565d1ca7 in vm_execute (frame_ctx_p=0xffffcac0) at jerryscript/jerry-core/vm/vm.c:4042
#10 0x565d2283 in vm_run (bytecode_header_p=0xf5500e10, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0xffffcd30, arg_list_len=1)
    at jerryscript/jerry-core/vm/vm.c:4150
#11 0x56649d38 in ecma_op_function_call_simple (func_obj_p=0xf5f00820, this_arg_value=72, arguments_list_p=0xffffcd30, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:854
#12 0x5664a6b5 in ecma_op_function_call (func_obj_p=0xf5f00820, this_arg_value=72, arguments_list_p=0xffffcd30, arguments_list_len=1)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1053
#13 0x5661120f in opfunc_call.lto_priv.457 (frame_ctx_p=0xffffcd00) at jerryscript/jerry-core/vm/vm.c:773
#14 0x565d1d0b in vm_execute (frame_ctx_p=0xffffcd00) at jerryscript/jerry-core/vm/vm.c:4048
#15 0x565d2283 in vm_run (bytecode_header_p=0xf5500dd0, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4150
#16 0x5660f85b in vm_run_global (bytecode_p=0xf5500dd0) at jerryscript/jerry-core/vm/vm.c:330
#17 0x5669197e in jerry_run (func_val=4126148691) at jerryscript/jerry-core/api/jerry.c:596
#18 0x5668df68 in main (argc=2, argv=0xffffd1c4) at jerryscript/jerry-main/main-unix.c:759
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3665.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser-expr.c [hunk 1]
```diff
@@ -2765,6 +2765,18 @@ parser_pattern_process_assignment (parser_context_t *context_p, /**< context */
...
+           CBC_EXT_ITERATOR_STEP -> CBC_EXT_ITERATOR_STEP_3
+           CBC_EXT_REST_INITIALIZER -> CBC_EXT_ITERATOR_STEP_3 */
+        if (stack_difference == 1
+            && context_p->last_cbc_opcode == CBC_PUSH_PROP_LITERAL
+            && context_p->last_cbc.literal_type == LEXER_IDENT_LITERAL)
+        {
+          stack_difference++;
+        }
+
         if (context_p->last_cbc_opcode == CBC_PUSH_PROP_LITERAL_LITERAL)
```
Comment (galpeter) [inline jerry-core/parser/js/js-parser-expr.c:2780]: Would it make sense to make this `if` to `else if`? If I read this correctly: if the first check is true, then this check is not needed.

Comment (rerobika) [reply jerry-core/parser/js/js-parser-expr.c]: I've reworked the PR, now this check is no longer needed.
