### PR TITLE
Fix PropertyDefinition parsing in ObjectInitializer

### LINKED ISSUE #3822: Assertion 'context_p->token.type == LEXER_RIGHT_BRACE || context_p->token.type == LEXER_ASSIGN || context_p->token.type == LEXER_COMMA' in parser_parse_object_initializer
###### JerryScript revision
d06c3a7

###### Build platform
Ubuntu 16.04.6 LTS (Linux 4.15.0-99-generic x86_64)

###### Build steps
```
python tools/build.py --profile=es2015-subset --lto=off --compile-flag=-g \
--error-messages=on --debug --compile-flag=-g --strip=off --logging=on \
--compile-flag=-fsanitize=address --stack-limit=15
```

###### Test case
```
function f ({array, 'a', { value: 'foo', enumerable: true } : 36})
{}
```

###### Output
```
ICE: Assertion 'context_p->token.type == LEXER_RIGHT_BRACE || context_p->token.type == LEXER_ASSIGN || context_p->token.type == LEXER_COMMA' failed at /home/JerryScript/jerryscript/jerry-core/parser/js/js-parser-expr.c(parser_parse_object_initializer):3230.
Error: ERR_FAILED_INTERNAL_ASSERTION
Aborted (core dumped)
```

Credits: This vulnerability is detected by chong from OWL337.

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3822.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser-expr.c [hunk 1]
```diff
@@ -888,6 +888,11 @@ parser_reparse_as_common_identifier (parser_context_t *context_p, /**< context *
                                      parser_line_counter_t start_line, /**< start line */
                                      parser_line_counter_t start_column) /**< start column */
 {
+  if (context_p->token.lit_location.type != LEXER_IDENT_LITERAL)
+  {
+    parser_raise_error (context_p, PARSER_ERR_IDENTIFIER_EXPECTED);
+  }
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-expr.c:894]: I would add an explanation that `context_p->token.lit_location.char_p` is showing the character after the string start, so it is not suitable for reparsing.

There is an `if` below:
```
if (context_p->token.type != LEXER_LITERAL
      || context_p->token.lit_location.type != LEXER_IDENT_LITERAL)
```
I think we don't need the `context_p->token.lit_location.type != LEXER_IDENT_LITERAL` after this change.

Comment (rerobika) [reply jerry-core/parser/js/js-parser-expr.c:894]: Good idea!
