### PR TITLE
Tagged template literal array should be marked after construction

### LINKED ISSUE #4385: Assertion 'array_object_p->u.array.length_prop_and_hole_count & ECMA_ARRAY_TEMPLATE_LITERAL' failed at ecma_collection_free_template_literal
###### JerryScript revision

9676500addbcc5974bf81f7b3726230d26f5c1a5

###### Build platform

Ubuntu 18.04.5 LTS (Linux 4.15.0-128-generic x86_64)

###### Build steps

```sh
./tools/build.py --clean --debug --logging=on
```

###### Test case

```js
P`${*\x10$
```

###### Execution steps & output

```
$ ./build/bin/jerry test.js 
ICE: Assertion 'array_object_p->u.array.length_prop_and_hole_count & ECMA_ARRAY_TEMPLATE_LITERAL' failed at jerryscript/jerry-core/ecma/base/ecma-helpers-collection.c(ecma_collection_free_template_literal):98.
Error: ERR_FAILED_INTERNAL_ASSERTION
Aborted (core dumped)
```

###### Backtrace

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a22921 in __GI_abort () at abort.c:79
#2  0x000055555555f76f in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#3  0x00005555555ad43c in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#4  0x00005555555ad48e in jerry_assert_fail (assertion=0x555555633670 "array_object_p->u.array.length_prop_and_hole_count & ECMA_ARRAY_TEMPLATE_LITERAL", 
    file=0x555555633618 "jerryscript/jerry-core/ecma/base/ecma-helpers-collection.c", 
    function=0x55555560e920 <__func__.4427.lto_priv.171> "ecma_collection_free_template_literal", line=98) at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#5  0x00005555556034e4 in ecma_collection_free_template_literal (collection_p=0x55555584b588 <jerry_global_heap+872>)
    at jerryscript/jerry-core/ecma/base/ecma-helpers-collection.c:98
#6  0x00005555555b5670 in parser_raise_error (context_p=0x7fffffffd670, error=PARSER_ERR_PRIMARY_EXP_EXPECTED) at jerryscript/jerry-core/parser/js/js-parser.c:2756
#7  0x0000555555570565 in parser_parse_unary_expression (context_p=0x7fffffffd670, grouping_level_p=0x7fffffffd420) at jerryscript/jerry-core/parser/js/js-parser-expr.c:2320
#8  0x00005555555738db in parser_parse_expression (context_p=0x7fffffffd670, options=0) at jerryscript/jerry-core/parser/js/js-parser-expr.c:3961
#9  0x000055555556f2f3 in parser_parse_tagged_template_literal (context_p=0x7fffffffd670) at jerryscript/jerry-core/parser/js/js-parser-expr.c:1823
#10 0x00005555555709fa in parser_process_unary_expression (context_p=0x7fffffffd670, grouping_level=0) at jerryscript/jerry-core/parser/js/js-parser-expr.c:2487
#11 0x0000555555573908 in parser_parse_expression (context_p=0x7fffffffd670, options=2) at jerryscript/jerry-core/parser/js/js-parser-expr.c:3970
#12 0x000055555557366e in parser_parse_block_expression (context_p=0x7fffffffd670, options=0) at jerryscript/jerry-core/parser/js/js-parser-expr.c:3910
#13 0x000055555555b52a in parser_parse_statements (context_p=0x7fffffffd670) at jerryscript/jerry-core/parser/js/js-parser-statm.c:3232
#14 0x00005555555b3fef in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x5555558cd4a0 "P`${*\\x10$\n", source_size=11, resource_name=593, parse_opts=0, error_location_p=0x7fffffffd8ec)
    at jerryscript/jerry-core/parser/js/js-parser.c:2004
#15 0x00005555555b56d7 in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x5555558cd4a0 "P`${*\\x10$\n", source_size=11, resource_name=593, parse_opts=0)
    at jerryscript/jerry-core/parser/js/js-parser.c:2799
#16 0x00005555555f8acd in jerry_parse (resource_name_p=0x7fffffffe0b6 "test3.js", resource_name_length=8, source_p=0x5555558cd4a0 "P`${*\\x10$\n", source_size=11, parse_opts=0)
    at jerryscript/jerry-core/api/jerry.c:459
#17 0x00005555555f5e8f in main (argc=2, argv=0x7fffffffdcb8) at jerryscript/jerry-main/main-unix.c:112
```

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #4385.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by zherczeg** [comment]
Is this a ref counting issue? What is happening here exactly?

**Comment by rerobika** [comment]
@zherczeg Template literal arrays are not freezed until the whole template is not parsed. Until now the freezing process marked the arrays with `ECMA_ARRAY_TEMPLATE_LITERAL`. However any syntaxerror can happen during parsing the template literal. At this point the template collection is freed by `parser_raise_error` cleanup part via `ecma_collection_free_template_literal`. But this function requires that each element of the collection must be marked with `ECMA_ARRAY_TEMPLATE_LITERAL`.

File: jerry-core/parser/js/js-parser-tagged-template-literal.c [hunk 1]
```diff
@@ -110,6 +110,9 @@ parser_new_tagged_template_literal (ecma_object_t **raw_strings_p) /**< [out] ra
   ecma_object_t *template_obj_p = ecma_op_new_array_object (0);
   *raw_strings_p = ecma_op_new_array_object (0);
 
+  ((ecma_extended_object_t *) template_obj_p)->u.array.length_prop_and_hole_count |= ECMA_ARRAY_TEMPLATE_LITERAL;
+  ((ecma_extended_object_t *) *raw_strings_p)->u.array.length_prop_and_hole_count |= ECMA_ARRAY_TEMPLATE_LITERAL;
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-tagged-template-literal.c:114]: Check expected value with a bitset and modify it with an assign

File: jerry-core/parser/js/js-parser-tagged-template-literal.c [hunk 2]
```diff
@@ -129,7 +132,6 @@ parser_tagged_template_literal_freeze_array (ecma_object_t *obj_p)
   ecma_op_ordinary_object_prevent_extensions (obj_p);
   ecma_extended_object_t *ext_obj_p = (ecma_extended_object_t *) obj_p;
   ext_obj_p->u.array.length_prop_and_hole_count &= (uint32_t) ~ECMA_PROPERTY_FLAG_WRITABLE;
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-tagged-template-literal.c:134]: Delete this line as well.

**Review by zherczeg — CHANGES_REQUESTED** [review]

File: jerry-core/parser/js/js-parser-tagged-template-literal.c (hunk 2 above)
Comment (rerobika) [reply jerry-core/parser/js/js-parser-tagged-template-literal.c:134]: After the rewrite I cannot delete it from here, since `ECMA_PROPERTY_FLAG_WRITABLE` flags should be kept until the array if frozen. If we remove it at the beginning we cannot add properties to the array. I'd keep it here.

Comment (zherczeg) [reply jerry-core/parser/js/js-parser-tagged-template-literal.c:140]: Optionally we could use the same technique as above: set the correct value directly. It is faster than flipping a flag (read/write). It is up to you.

**Review by zherczeg — APPROVED** [review]
LGTM

**Comment by rerobika** [comment]
@zherczeg The length of the array should me calculated into the value that we want to assign to delete writable flag so for the readability I'd leave as it.

File: jerry-core/parser/js/js-parser-tagged-template-literal.c [hunk 3]
```diff
@@ -110,6 +110,16 @@ parser_new_tagged_template_literal (ecma_object_t **raw_strings_p) /**< [out] ra
   ecma_object_t *template_obj_p = ecma_op_new_array_object (0);
   *raw_strings_p = ecma_op_new_array_object (0);
 
+  ecma_extended_object_t *template_ext_obj_p = (ecma_extended_object_t *) template_obj_p;
+  ecma_extended_object_t *raw_ext_obj_p = (ecma_extended_object_t *) *raw_strings_p;
+
+  const uint8_t flags = ECMA_PROPERTY_TYPE_VIRTUAL | ECMA_PROPERTY_FLAG_WRITABLE | ECMA_FAST_ARRAY_FLAG;
+  JERRY_ASSERT (template_ext_obj_p->u.array.length_prop_and_hole_count == flags);
+  JERRY_ASSERT (raw_ext_obj_p->u.array.length_prop_and_hole_count== flags);
```
Comment (akosthekiss) [inline jerry-core/parser/js/js-parser-tagged-template-literal.c:118]: (minor style) space missing from before == (it's interesting that the style checker did not catch this)

**Review by akosthekiss — CHANGES_REQUESTED** [review]

File: jerry-core/parser/js/js-parser-tagged-template-literal.c (hunk 3 above)
Comment (rerobika) [reply jerry-core/parser/js/js-parser-tagged-template-literal.c]: Thanks! (it's quite interesing)

**Review by akosthekiss — APPROVED** [review]
LGTM
