### PR TITLE
Fix value release in ecma_op_is_concat_spreadable

### LINKED ISSUE #3356: Assertion ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p) in ecma_free_string_list
###### JerryScript revision
62356796

###### Build platform
Linux-4.15.0-62-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
var alpha = []; 
var $ = {[$] : $} 
obj = {}  
obj[ Symbol.isConcatSpreadable ] = "\O"  
alpha.concat(obj) 
```

###### Output
```text
Script Error: ReferenceError: id_2 is not defined
ICE: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_string_list):75.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b78e in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x56607f14 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x56607f55 in jerry_assert_fail (assertion=0x566df6a0 "ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)", file=0x566df620 "jerryscript/jerry-core/ecma/base/ecma-literal-storage.c", function=0x566a2640 <__func__.5475.lto_priv.743> "ecma_free_string_list", line=75) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x566578fe in ecma_free_string_list (string_list_cp=4124051312) at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:75
#7  0x56657b31 in ecma_finalize_lit_storage () at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:121
#8  0x566566e7 in ecma_finalize () at jerryscript/jerry-core/ecma/base/ecma-init-finalize.c:68
#9  0x5667c3d2 in jerry_cleanup () at jerryscript/jerry-core/api/jerry.c:236
#10 0x5667a339 in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:938
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### LINKED ISSUE #3361: Assertion JERRY_CONTEXT (jmem_heap_allocated_size) == 0 in jmem_heap_finalize
###### JerryScript revision
62356796

###### Build platform
Linux-4.15.0-62-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
var fakeArray = { [ Symbol ] : 0};
fakeArray[ Symbol.isConcatSpreadable ] = 2.756;
[].concat(fakeArray);
```

###### Output
```text
Script Error: ReferenceError: id_2 is not defined
ICE: Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed at jerryscript/jerry-core/jmem/jmem-heap.c(jmem_heap_finalize):107.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b78e in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x56607f14 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x56607f55 in jerry_assert_fail (assertion=0x566d37a0 "JERRY_CONTEXT (jmem_heap_allocated_size) == 0", file=0x566d3740 "jerryscript/jerry-core/jmem/jmem-heap.c", function=0x566a7640 <__func__.4929.lto_priv.135> "jmem_heap_finalize", line=107) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x566070e5 in jmem_heap_finalize () at jerryscript/jerry-core/jmem/jmem-heap.c:107
#7  0x56606f15 in jmem_finalize () at jerryscript/jerry-core/jmem/jmem-allocator.c:170
#8  0x5667c687 in jerry_cleanup () at jerryscript/jerry-core/api/jerry.c:252
#9  0x5667a339 in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:938
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by szilagyiadam**
Fixes #3356 
Fixes #3361 

JerryScript-DCO-1.0-Signed-off-by: Adam Szilagyi aszilagy@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/operations/ecma-objects.c [hunk 1]
```diff
@@ -2565,7 +2565,9 @@ ecma_op_is_concat_spreadable (ecma_value_t arg) /**< argument */
 
   if (!ecma_is_value_undefined (spreadable))
   {
-    return ecma_make_boolean_value (ecma_op_to_boolean (spreadable));
+    const bool to_bool = ecma_op_to_boolean (spreadable);
+    ecma_free_value (spreadable);
+    return ecma_make_boolean_value (to_bool);
```
Comment (galpeter) [inline jerry-core/ecma/operations/ecma-objects.c]: Can we add a test case for this?

File: tests/jerry/es2015/regression-test-issue.3356.js [hunk 2]
```diff
@@ -0,0 +1,19 @@
+// Copyright JS Foundation and other contributors, http://js.foundation
```
Comment (galpeter) [inline tests/jerry/es2015/regression-test-issue.3356.js]: The file name is incorrect. It should be `regression-test-issue-3356.js` , notice the dash before the issue number.
