### PR TITLE
Early return when the scanner throws an error while parsing an invalid function identifier

### LINKED ISSUE #3454: Assertion source_p != NULL in scanner_insert_info
###### JerryScript revision
d0b4e7dd

###### Build platform
Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
"use strict"
var $ = function yield() {}
```

###### Output
```text
ICE: Assertion 'source_p != NULL' failed at jerryscript/jerry-core/parser/js/js-scanner-util.c(scanner_insert_info):200.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b7cd in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x5664976b in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x566497ac in jerry_assert_fail (assertion=0x566e0a40 "source_p != NULL", file=0x566e08c0 "jerryscript/jerry-core/parser/js/js-scanner-util.c", function=0x566bc300 <__func__.5794.lto_priv.499> "scanner_insert_info", line=200) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x5660993e in scanner_insert_info (context_p=0xffffc4b0, source_p=0x0, size=13) at jerryscript/jerry-core/parser/js/js-scanner-util.c:200
#7  0x5660b639 in scanner_pop_literal_pool (context_p=0xffffc4b0, scanner_context_p=0xffffc2f0) at jerryscript/jerry-core/parser/js/js-scanner-util.c:619
#8  0x56621e20 in scanner_scan_all (context_p=0xffffc4b0, arg_list_p=0x0, arg_list_end_p=0x0, source_p=0x56729cc0 <buffer.lto_priv> "\"use strict\" \nvar f = function yield ( i ) { if ( i = 0 ) return yield ( i + 1 ) \n\nreturn 39 \n} ; \n ", source_end_p=0x56729d24 <buffer.lto_priv+100> "") at jerryscript/jerry-core/parser/js/js-scanner.c:3325
#9  0x56605036 in parser_parse_source (arg_list_p=0x0, arg_list_size=0, source_p=0x56729cc0 <buffer.lto_priv> "\"use strict\" \nvar f = function yield ( i ) { if ( i = 0 ) return yield ( i + 1 ) \n\nreturn 39 \n} ; \n ", source_size=100, parse_opts=0, error_location_p=0xffffc6c0) at jerryscript/jerry-core/parser/js/js-parser.c:1918
#10 0x566090ce in parser_parse_script (arg_list_p=0x0, arg_list_size=0, source_p=0x56729cc0 <buffer.lto_priv> "\"use strict\" \nvar f = function yield ( i ) { if ( i = 0 ) return yield ( i + 1 ) \n\nreturn 39 \n} ; \n ", source_size=100, parse_opts=0, bytecode_data_p=0xffffc780) at jerryscript/jerry-core/parser/js/js-parser.c:2527
#11 0x5669a4bf in jerry_parse (resource_name_p=0xffffcd88 "/home/reni/.fuzzinator_33766//jerryscript/picireny/87744282367244666083406669132424056753.js", resource_name_length=92, source_p=0x56729cc0 <buffer.lto_priv> "\"use strict\" \nvar f = function yield ( i ) { if ( i = 0 ) return yield ( i + 1 ) \n\nreturn 39 \n} ; \n ", source_size=100, parse_opts=0) at jerryscript/jerry-core/api/jerry.c:445
#12 0x56697243 in main (argc=2, argv=0xffffcb14) at jerryscript/jerry-main/main-unix.c:731
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
Fixes #3454

JerryScript-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-scanner-util.c [hunk 1]
```diff
@@ -455,6 +455,17 @@ scanner_pop_literal_pool (parser_context_t *context_p, /**< context */
 {
   scanner_literal_pool_t *literal_pool_p = scanner_context_p->active_literal_pool_p;
   scanner_literal_pool_t *prev_literal_pool_p = literal_pool_p->prev_p;
+
+  if (literal_pool_p->source_p == NULL)
+  {
+    JERRY_ASSERT (literal_pool_p->status_flags & SCANNER_LITERAL_POOL_FUNCTION);
+    scanner_context_p->active_literal_pool_p = literal_pool_p->prev_p;
+
+    parser_list_free (&literal_pool_p->literal_pool);
```
Comment (zherczeg) [inline jerry-core/parser/js/js-scanner-util.c]: I think if source_p is NULL, there cannot be any item in the literal pool. Just add an assert.

Comment (DanielBallaSZTE) [reply jerry-core/parser/js/js-scanner-util.c]: True.
