### PR TITLE
Fix helper function for rounding numbers

### LINKED ISSUE #1701: stack-buffer-overflow in ecma_builtin_number_prototype_helper_round
###### Jerry version:

```
Checked revision: 3ff9a7d
Build command: ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --compile-flag=-g --jerry-libc=off --static-link=off --strip=off --system-allocator=on --linker-flag=-fuse-ld=gold --error-messages=on
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
Number(982).toPrecision(1)
```

###### Backtrace:

```
=================================================================
==29528==ERROR: AddressSanitizer: stack-buffer-overflow on address 0xf54b4b5f at pc 0x080bc8d2 bp 0xffabc658 sp 0xffabc648
READ of size 1 at 0xf54b4b5f thread T0
    #0 0x80bc8d1 in ecma_builtin_number_prototype_helper_round jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:159
    #1 0x80bc8d1 in ecma_builtin_number_prototype_object_to_precision.lto_priv.483 jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:845
    #2 0x80c499a in ecma_builtin_number_prototype_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.inc.h:37
    #3 0x80ea9f8 in ecma_builtin_dispatch_routine.lto_priv.626 jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:91
    #4 0x80e533d in ecma_builtin_dispatch_call jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:844
    #5 0x80b1356 in ecma_op_function_call jerryscript/jerry-core/ecma/operations/ecma-function-object.c:461
    #6 0x807d096 in opfunc_call.lto_priv.236 jerryscript/jerry-core/vm/vm.c:411
    #7 0x80689ad in vm_execute jerryscript/jerry-core/vm/vm.c:2682
    #8 0x8068f32 in vm_run jerryscript/jerry-core/vm/vm.c:2761
    #9 0x807c73f in vm_run_global jerryscript/jerry-core/vm/vm.c:231
    #10 0x810e219 in jerry_run jerryscript/jerry-core/jerry.c:387
    #11 0x810d608 in main jerryscript/jerry-main/main-unix.c:731
    #12 0xf6fee636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #13 0x8048e50  (jerryscript/build/bin/jerry+0x8048e50)

Address 0xf54b4b5f is located in stack of thread T0 at offset 95 in frame
    #0 0x80bc2d7 in ecma_builtin_number_prototype_object_to_precision.lto_priv.483 jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:769

  This frame has 2 object(s):
    [32, 36) 'exponent'
    [96, 160) 'digits' <== Memory access at offset 95 underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-overflow jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c:159 ecma_builtin_number_prototype_helper_round
Shadow bytes around the buggy address:
  0x3ea96910: f5 f5 f5 f5 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ea96920: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x3ea96930: f5 f5 f5 f5 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ea96940: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x3ea96950: f5 f5 f5 f5 00 00 00 00 00 00 00 00 00 00 00 00
=>0x3ea96960: f1 f1 f1 f1 04 f4 f4 f4 f2 f2 f2[f2]00 00 00 00
  0x3ea96970: 00 00 00 00 f3 f3 f3 f3 00 00 00 00 00 00 00 00
  0x3ea96980: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5
  0x3ea96990: f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 f5 00 00 00 00
  0x3ea969a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3ea969b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==29528==ABORTING
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

### PR DESCRIPTION
**Pull request by robertsipka**
Fixes #1701

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c [hunk 1]
```diff
@@ -154,7 +154,7 @@ ecma_builtin_number_prototype_helper_round (lit_utf8_byte_t *digits_p, /**< [in,
     int i = 1;
 
     /* Handle curry number. */
```
Comment (dbatyai) [inline jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c]: Even though I like curry, can we please fix this comment while we're here?

File: jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c [hunk 2]
```diff
@@ -154,7 +154,7 @@ ecma_builtin_number_prototype_helper_round (lit_utf8_byte_t *digits_p, /**< [in,
...
-    for (; i < (int) num_digits; i++)
+    for (; i < (int) num_digits && i <= round_num; i++)
```
Comment (dbatyai) [inline jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c]: `round_num` will always be less than `num_digits`, because of the `if` on line 145, so the condition for `num_digits` is unnecessary.

File: jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c [hunk 3]
```diff
@@ -164,7 +164,7 @@ ecma_builtin_number_prototype_helper_round (lit_utf8_byte_t *digits_p, /**< [in,
     }
 
     /* Prepend highest digit */
-    if (i >= (int) num_digits)
+    if (i >= (int) num_digits || i > round_num)
```
Comment (dbatyai) [inline jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c]: Same here, the condition for `round_num` is enough.

Comment (robertsipka) [inline jerry-core/ecma/builtin-objects/ecma-builtin-number-prototype.c]: @dbatyai : You're right, thanks! I've updated it accordingly.
