### PR TITLE
CBC_PUSH_THIS should not be mutated in array literal parsing.

### LINKED ISSUE #3650: A question about creating arrays.
When running this test case blow, jerry threw an exception in line 5. Why does this happen?Is it a bug of jerry?

###### JerryScript revision
[996bf76](https://github.com/jerryscript-project/jerryscript/commit/996bf76f5956c65342c1726d3f629fbea41320ab)

###### Build platform
    Ubuntu 16.04.6 LTS (Linux 4.15.0-55-generic x86_64)

###### Build steps
    python tools/build.py --clean --debug --logging=on --line-info=on --error-messages=on --cpointer-32bit=on --mem-heap=1572864 --profile=es2015-subset

###### Test case
```
var NISLFuzzingFunc = function(u) {
     print([u = u-1, this]);
     print([this, 1]);
     print([1, u = u-1]);
     print([this, u = u-1]);
 };
 var NISLParameter0 = 2;
 NISLFuzzingFunc(NISLParameter0);

```

###### Execution steps
    build/bin/jerry testcase.js

###### Output
```
1, [object Object]
[object Object], 1
1, 0
Exception backtrace:
    0: testcase.js:5
    1: testcase.js:8
Script Error: ReferenceError: Undefined reference.
```
###### Expected behavior
```
1, [object Object]
[object Object], 1
1, 0
[object Object], -1
```

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3650, and slightly reverts the changes of #3594.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser-expr.c [hunk 1]
```diff
@@ -281,6 +282,11 @@ parser_parse_array_literal (parser_context_t *context_p) /**< context */
 
       parser_parse_expression (context_p, PARSE_EXPR_NO_COMMA);
 
+      if (context_p->last_cbc_opcode == CBC_PUSH_THIS)
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-expr.c]: Shouldn't be this inside the `if (context_p->token.type == LEXER_COMMA)` condition?

Comment (zherczeg) [reply jerry-core/parser/js/js-parser-expr.c]: Hm, probably irrelevant where it is. Ok, let it be this way.

Comment (rerobika) [reply jerry-core/parser/js/js-parser-expr.c]: Good idea.
