### PR TITLE
Fix assertion fail in typedarray_prototype_to locale_string

### LINKED ISSUE #4217: Assertion '!ECMA_IS_VALUE_ERROR (element_obj) in ecma_builtin_typedarray_prototype_to_locale_string_helper
###### JerryScript revision
3c723c9bc1aec08a54bc44bba7987e4324f440e4
(latest master - 2020.09.21.)

###### Build platform
Ubuntu 18.04.5 LTS (Linux 4.15.0-112-generic x86_64)

###### Build steps
tools/build.py --debug --logging=on --error-messages=on --line-info=on

###### Test case
found by test262-esnext tests:
- built-ins/TypedArray/prototype/toLocaleString/BigInt/calls-tolocalestring-from-each-value.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/calls-tostring-from-each-value.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/calls-valueof-from-each-value.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/get-length-uses-internal-arraylength.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-firstelement-tolocalestring.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-firstelement-tostring.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-firstelement-valueof.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-nextelement-tolocalestring.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-nextelement-tostring.js
- built-ins/TypedArray/prototype/toLocaleString/BigInt/return-abrupt-from-nextelement-valueof.js

###### Output
```
ICE: Assertion '!ECMA_IS_VALUE_ERROR (element_obj)' failed at /home/oszi/jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c(ecma_builtin_typedarray_prototype_to_locale_string_helper):1566.
Error: ERR_FAILED_INTERNAL_ASSERTION
```
###### Expected behavior
no assert

### PR DESCRIPTION
**Pull request by orkvi**
Change typedarray_prototype_to_locale_string_helper to use ecma_op_invoke_magic_id instead

Fixes #4217 

JerryScript-DCO-1.0-Signed-off-by: Virag Orkenyi orkvi@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c [hunk 1]
```diff
@@ -1559,59 +1559,25 @@ ecma_builtin_typedarray_prototype_to_locale_string_helper (ecma_typedarray_info_
 {
   ecma_value_t ret_value = ECMA_VALUE_EMPTY;
```
Comment (rerobika) [inline jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:1560]: This variable is not needed anymore.

File: jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c [hunk 2]
```diff
@@ -1559,59 +1559,25 @@ ecma_builtin_typedarray_prototype_to_locale_string_helper (ecma_typedarray_info_
...
-  else
+  if (JERRY_UNLIKELY (str_p == NULL))
   {
-    ecma_free_value (func_value);
-    ret_value = ecma_raise_type_error (ECMA_ERR_MSG ("'toLocaleString' is missing or not a function."));
+    return ECMA_VALUE_ERROR;
   }
 
-  ecma_deref_object (element_obj_p);
+  ret_value = ecma_make_string_value (str_p);
```
Comment (rerobika) [inline jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:1580]: return with `ecma_make_string_value` directly.

**Review by rerobika — CHANGES_REQUESTED** [review]

**Review by rerobika — APPROVED** [review]
LGTM

**Review by dbatyai — APPROVED** [review]
LGTM
