### PR TITLE
Fix for null pointer dereference in jmem_heap_free_block

### LINKED ISSUE #2435: Null pointer dereference in jmem-heap
- Jerry Version:
f86d745

- Build command:
`python tools/build.py --profile=es2015-subset --jerry-libc=OFF --clean --strip OFF --compile-flag="-g" --compile-flag="-fsanitize=address"`

- OS:
Ubuntu 16.04

- Test case:
`(new Int8Array(0)).filter(parseInt)`

- Result:
```ASAN:SIGSEGV
  =================================================================
  ==7815==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x000000402bc1 bp 0x000000000193 sp 0x7fff3cb1ba80 T0)
      #0 0x402bc0 in jmem_heap_free_block jerry-core/jmem/jmem-heap.c:463
      #1 0x422215  (build/bin/jerry+0x422215)
      #2 0x428231 in ecma_builtin_dispatch_routine jerry-core/ecma/builtin-objects/ecma-builtins.c:906
      #3 0x428231 in ecma_builtin_dispatch_call jerry-core/ecma/builtin-objects/ecma-builtins.c:931
      #4 0x428231 in ecma_op_function_call jerry-core/ecma/operations/ecma-function-object.c:495
      #5 0x4613f5 in opfunc_call jerry-core/vm/vm.c:436
      #6 0x4613f5 in vm_execute jerry-core/vm/vm.c:3008
      #7 0x461fda in vm_run jerry-core/vm/vm.c:3092
      #8 0x424411 in vm_run_eval jerry-core/vm/vm.c:270
      #9 0x424411 in ecma_op_eval_chars_buffer jerry-core/ecma/operations/ecma-eval.c:111
      #10 0x40274f in jerry_eval jerry-core/api/jerry.c:570
      #11 0x40274f in main jerry-main/main-unix.c:810
      #12 0x7f749b68f82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
      #13 0x403148 in _start (build/bin/jerry+0x403148)

  AddressSanitizer can not provide additional info.
  SUMMARY: AddressSanitizer: SEGV jerry-core/jmem/jmem-heap.c:463 jmem_heap_free_block
  ==7815==ABORTING
```

- Immediate cause:
It seems that this bug is caused by triggering undefined behavior at jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:598. The second passed argument is NULL. This causes NULL dereference and allows GCC to optimize out subsequent checks for NULL. This further causes writing to null pointer, which results in a segmentation fault. Note, that because this bug occurs due to gcc optimizing out a check for NULL, this may not be reproducible with a debug build.

Please confirm if you can reproduce this issue.

This bug was discovered by Marcin Dominiak and Wojciech Rauner.

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
Fixes #2435.

JerryScript-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

**Comment by dominiakm** [comment]
Hi,
I'm the original poster of the issue you are fixing here.

While this change does prevent segfault, undefined behavior is still triggered at jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:598

This is because behavior of memcpy is undefined if the second argument is NULL.
This can be verified by using UBSan (undefined behavior sanitizer).
To do this, build jerryscript with
`python tools/build.py --profile=es2015-subset --jerry-libc=off --lto=off --compile-flag="-fsanitize=undefined"`

Running the example provided by me shows the following message:
`jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c:598:7: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/x86_64-linux-gnu/bits/string3.h:53:10: runtime error: null pointer passed as argument 2, which is declared to never be null.`

**Comment by dominiakm** [comment]
The implementation of `filter` (from jerryscript/jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c) calls `memcpy` (in line 598) with the second argument (`pass_value_list_p`) being `NULL`.

Current implementation (without this commit) in JMEM_FINALIZE_LOCAL_ARRAY checks if `var_name` (`pass_value_list_p` in this case) is `NULL`. However, this check is optimized out, because of the call to `memcpy`. This is because gcc assumes, that that the second argument of memcpy is never NULL.

The default build for jerryscript enbales gcc optimisation `-fdelete-null-pointer-checks`, which removes the check from JMEM_FINALIZE_LOCAL_ARRAY  -- because of the call to memcpy.

**Comment by DanielBallaSZTE** [comment]
I've added an early return to resolve this issue, and the test case as well.

**Comment by dominiakm** [comment]
This version no longer triggers undefined behavior.

File: jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c [hunk 1]
```diff
@@ -588,6 +588,11 @@ ecma_builtin_typedarray_prototype_filter (ecma_value_t this_arg, /**< this argum
 
     ret_value = ecma_op_create_typedarray_with_type_and_length (obj_p, pass_num);
 
+    if (len == 0)
+    {
+      return ret_value;
+    }
+
```
Comment (zherczeg) [inline jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: No need an extra newline.

File: jerry-core/jmem/jmem.h [hunk 2]
```diff
@@ -195,16 +195,11 @@ void jmem_run_free_unused_memory_callbacks (jmem_free_unused_memory_severity_t s
...
   { \
-    JERRY_ASSERT (var_name ## ___size != 0); \
-    \
+    JERRY_ASSERT (var_name != NULL); \
     jmem_heap_free_block (var_name, var_name ## ___size); \
   } \
-  else \
-  { \
-    JERRY_ASSERT (var_name ## ___size == 0); \
-  } \
```
Comment (zherczeg) [inline jerry-core/jmem/jmem.h]: This change should be removed.

File: jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c [hunk 3]
```diff
@@ -588,6 +588,10 @@ ecma_builtin_typedarray_prototype_filter (ecma_value_t this_arg, /**< this argum
 
     ret_value = ecma_op_create_typedarray_with_type_and_length (obj_p, pass_num);
 
+    if (len == 0)
+    {
+      return ret_value;
+    }
```
Comment (zherczeg) [inline jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: Hm, why this is not before the define local array?

Comment (DanielBallaSZTE) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: Because in some cases we can not return with `ECMA_VALUE_EMPTY`

Comment (zherczeg) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: so we return with a new typedarray?

Comment (zherczeg) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: actually we return from a macro enclosed block, and that is not necessarily healthy.

Comment (DanielBallaSZTE) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: Yes but we only return from there when the length is 0, therefore the enclosing macro would basically do nothing

Comment (DanielBallaSZTE) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: And yes, we have to give back a 0 length typedarray in that case

Comment (zherczeg) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: The problem is we might change silently the macro and we have a hidden bug. Creating and returning with an empty array early should be easy.

Comment (DanielBallaSZTE) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: Yes, that is definitely right, it would just mean a bit if a code duplication there.

Comment (zherczeg) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: The compiler should handle that. Since it is a single line, I would not even call it a duplication.

Comment (DanielBallaSZTE) [reply jerry-core/ecma/builtin-objects/typedarray/ecma-builtin-typedarray-prototype.c]: Yeah you convinced me there, I'm updating the PR
