### PR TITLE
Fix new.target saving in OrdinaryObject.[[Construct]]

### LINKED ISSUE #4059: Assertion 'JERRY_CONTEXT (current_new_target) == NULL' in ecma_finalize
###### JerryScript revision
da5b058

###### Build platform
Ubuntu 16.04.6 LTS (Linux 4.15.0-99-generic x86_64)

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
 --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
 --compile-flag=-fno-common --compile-flag=-g --strip=off \
 --system-allocator=on --logging=on --linker-flag=-fuse-ld=gold \
 --error-messages=on --profile=es2015-subset --lto=off 
```
###### Test case
```
function print(value){}

print(String.fromCharCode(new new Proxy(Function(), { get:String.fromCharCode}), 0, false, 67));

```
###### Output
```
Script Error: TypeError: Cannot convert a Symbol value to a number.
ICE: Assertion 'JERRY_CONTEXT (current_new_target) == NULL' failed at /home/jerryscript/jerry-core/ecma/base/ecma-init-finalize.c(ecma_finalize):76.
Error: ERR_FAILED_INTERNAL_ASSERTION
Aborted (core dumped)

```

Credits: This vulnerability is detected by chong from OWL337.

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #4059.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/operations/ecma-function-object.c [hunk 1]
```diff
@@ -1350,6 +1350,9 @@ ecma_op_function_construct (ecma_object_t *func_obj_p, /**< Function object */
     /* 5.b */
     if (JERRY_UNLIKELY (proto_p == NULL))
     {
+#if ENABLED (JERRY_ESNEXT)
```
Comment (galpeter) [inline jerry-core/ecma/operations/ecma-function-object.c:1353]: I was wondering: if we move the `1340-1341` lines from above just before the `.._call_simple` to avoid adding this here ? Would that change anything in the `ecma_op_get_prototype_from_constructor` or `ecma_create_object` internals?

Comment (rerobika) [reply jerry-core/ecma/operations/ecma-function-object.c]: That's a good idea.

**Comment by rerobika** [comment]
@galpeter Thanks for the review, I've updated the PR.
