### PR TITLE
Bugfix for #1671

### LINKED ISSUE #1671: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed in ecma_free_string_list
###### Jerry version:

```
Checked revision: 4420401
Build command: ./tools/build.py --clean --debug
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
Array.prototype.splice(0, 0, 0, "")
Array.prototype.shift()
Array.prototype.push("", 0, 1)
Array.prototype.sort(JSON.parse)
```

###### Backtrace:

```
ICE: Assertion 'ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)' failed at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c(ecma_free_string_list):42.
Error: ERR_FAILED_INTERNAL_ASSERTION
bt
#0  0x000000000046e2f4 in syscall_2 () at jerryscript/jerry-libc/target/posix/jerry-asm.S:59
#1  0x0000000000402760 in raise (sig=6) at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:91
#2  0x0000000000402732 in abort () at jerryscript/jerry-libc/target/posix/jerry-libc-target.c:77
#3  0x000000000041155d in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/targets/default/jerry-port-default-fatal.c:53
#4  0x000000000042c330 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:61
#5  0x000000000042c382 in jerry_assert_fail (assertion=0x471ae0 "ECMA_STRING_IS_REF_EQUALS_TO_ONE (string_p)", 
    file=0x471a80 "jerryscript/jerry-core/ecma/base/ecma-literal-storage.c", 
    function=0x488650 <__func__.3396.lto_priv.109> "ecma_free_string_list", line=42)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:85
#6  0x00000000004138d3 in ecma_free_string_list (string_list_p=0x692398 <jerry_global_heap+416>)
    at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:42
#7  0x0000000000413954 in ecma_finalize_lit_storage () at jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:59
#8  0x0000000000458283 in ecma_finalize () at jerryscript/jerry-core/ecma/base/ecma-init-finalize.c:62
#9  0x000000000046bb38 in jerry_cleanup () at jerryscript/jerry-core/jerry.c:177
#10 0x000000000046b9fb in main (argc=3, argv=0x7fffffffd388) at jerryscript/jerry-main/main-unix.c:829
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

### PR DESCRIPTION
**Pull request by rerobika**
Shifting array element down in the tree must be finished even if an error occurs

Fixes #1671

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c [hunk 1]
```diff
@@ -1113,16 +1113,17 @@ ecma_builtin_array_prototype_object_array_to_heap_helper (ecma_value_t array[],
     }
   }
 
+  /*
+   * Loop ended, either current child does not exist, or is less than swap.
+   * This means that 'swap' should be placed in the parent node.
+   * Note: Swapping array elements must be finished even if ret_value is empty
```
Comment (galpeter) [inline jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c]: I don't think we need this `Note:` part here.

Comment (rerobika) [inline jerry-core/ecma/builtin-objects/ecma-builtin-array-prototype.c]: I've removed it.
