### PR TITLE
Fix for-of block context creation for empty destructuring pattern

### LINKED ISSUE #3421: Assertion ecma_get_lex_env_type (lex_env_p) == ECMA_LEXICAL_ENVIRONMENT_DECLARATIVE in ecma_clone_decl_lexical_environment
###### JerryScript revision
1829d2df

###### Build platform
Linux-4.15.0-72-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
for (let [] of [[], []]);
```

###### Output
```text
ICE: Assertion 'ecma_get_lex_env_type (lex_env_p) == ECMA_LEXICAL_ENVIRONMENT_DECLARATIVE' failed at jerryscript/jerry-core/ecma/base/ecma-helpers.c(ecma_clone_decl_lexical_environment):331.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b549 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x56644e58 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x56644e99 in jerry_assert_fail (assertion=0x566eaa40 "ecma_get_lex_env_type (lex_env_p) == ECMA_LEXICAL_ENVIRONMENT_DECLARATIVE", file=0x566ea600 "jerryscript/jerry-core/ecma/base/ecma-helpers.c", function=0x566a9720 <__func__.5665.lto_priv.763> "ecma_clone_decl_lexical_environment", line=331) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x56679a59 in ecma_clone_decl_lexical_environment (lex_env_p=0xf5d007b0, copy_values=false) at jerryscript/jerry-core/ecma/base/ecma-helpers.c:331
#7  0x565d20f6 in vm_loop (frame_ctx_p=0xffffc6d0) at jerryscript/jerry-core/vm/vm.c:1467
#8  0x565e0a23 in vm_execute (frame_ctx_p=0xffffc6d0) at jerryscript/jerry-core/vm/vm.c:4070
#9  0x565e10a3 in vm_run (bytecode_header_p=0xf6301580, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4199
#10 0x56629c63 in vm_run_global (bytecode_p=0xf6301580) at jerryscript/jerry-core/vm/vm.c:286
#11 0x56695043 in jerry_run (func_val=4126148883) at jerryscript/jerry-core/api/jerry.c:595
#12 0x566917b0 in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:740
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3421.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser-statm.c [hunk 1]
```diff
@@ -1189,12 +1189,12 @@ parser_parse_for_statement_start (parser_context_t *context_p) /**< context */
       else
       {
         token_type = LEXER_KEYW_LET;
-        has_context = true;
+        has_context = context_p->next_scanner_info_p->source_p == context_p->source_p;
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-statm.c]: put parenthesis around `context_p->next_scanner_info_p->source_p == context_p->source_p`

Comment (rerobika) [reply jerry-core/parser/js/js-parser-statm.c]: Done!
