### PR TITLE
Remove bad assertion in ecma_builtin_json_str_helper

### LINKED ISSUE #2494: Assertion 'ecma_is_value_true (put_comp_val)' failed in ecma_builtin_json_str_helper
###### Jerry version:

```
Checked revision: 300e40ba
Build command: tools/build.py --debug --logging=on
```

###### OS:

```
Ubuntu 18.04, x86_64
```

###### Test case:

```javascript
Object.defineProperty(Object.prototype, "", {});
JSON.stringify()
```

###### Backtrace:

```
ICE: Assertion 'ecma_is_value_true (put_comp_val)' failed at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.c(ecma_builtin_json_str_helper):926.
Error: ERR_FAILED_INTERNAL_ASSERTION

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff7a24801 in __GI_abort () at abort.c:79
#2  0x000055555555f364 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-port/default/default-fatal.c:71
#3  0x000055555558ac1f in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#4  0x000055555558ac71 in jerry_assert_fail (assertion=0x5555555e0b58 "ecma_is_value_true (put_comp_val)", 
    file=0x5555555e0a58 "jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.c", 
    function=0x5555555cdf30 <__func__.4944.lto_priv.569> "ecma_builtin_json_str_helper", line=926)
    at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#5  0x00005555555b58a4 in ecma_builtin_json_str_helper (arg1=72, context=...)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.c:926
#6  0x00005555555b61ed in ecma_builtin_json_stringify (this_arg=291, arg1=72, arg2=72, arg3=72)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.c:1191
#7  0x00005555555b4528 in ecma_builtin_json_dispatch_routine (builtin_routine_id=59, this_arg_value=291, 
    arguments_list=0x7fffffffd7dc, arguments_number=0)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-json.inc.h:27
#8  0x00005555555b9152 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_JSON, builtin_routine_id=59, 
    this_arg_value=291, arguments_list_p=0x7fffffffd7dc, arguments_list_len=0)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:916
#9  0x00005555555b92a4 in ecma_builtin_dispatch_call (obj_p=0x5555558f14f0 <jerry_global_heap+320>, this_arg_value=291, 
    arguments_list_p=0x7fffffffd7dc, arguments_list_len=0)
    at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:941
#10 0x00005555555a04ad in ecma_op_function_call (func_obj_p=0x5555558f14f0 <jerry_global_heap+320>, this_arg_value=291, 
    arguments_list_p=0x7fffffffd7dc, arguments_list_len=0)
    at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:495
#11 0x0000555555594d6b in opfunc_call (frame_ctx_p=0x7fffffffd820) at jerryscript/jerry-core/vm/vm.c:436
#12 0x0000555555599dd1 in vm_execute (frame_ctx_p=0x7fffffffd820, arg_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:3006
#13 0x000055555559a070 in vm_run (bytecode_header_p=0x5555558f15b0 <jerry_global_heap+512>, this_binding_value=27, 
    lex_env_p=0x5555558f13e0 <jerry_global_heap+48>, parse_opts=0, arg_list_p=0x0, arg_list_len=0)
    at jerryscript/jerry-core/vm/vm.c:3090
#14 0x0000555555594996 in vm_run_global (bytecode_p=0x5555558f15b0 <jerry_global_heap+512>)
    at jerryscript/jerry-core/vm/vm.c:225
#15 0x00005555555bef1d in jerry_run (func_val=203) at jerryscript/jerry-core/api/jerry.c:533
#16 0x00005555555bd821 in main (argc=3, argv=0x7fffffffdc58) at jerryscript/jerry-main/main-unix.c:676
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by pmarkee**
Fixes #2494

JerryScript-DCO-1.0-Signed-off-by: Peter Marki marpeter@inf.u-szeged.hu

### CODE REVIEW

File: tests/jerry/regression-test-issue-2494.js [hunk 1]
```diff
@@ -0,0 +1,2 @@
+Object.defineProperty(Object.prototype, "", {});
```
Comment (LaszloLango) [inline tests/jerry/regression-test-issue-2494.js]: Please add a license header.

File: jerry-core/ecma/builtin-objects/ecma-builtin-json.c [hunk 2]
```diff
@@ -923,7 +923,12 @@ static ecma_value_t ecma_builtin_json_str_helper (const ecma_value_t arg1, /**<
                                                   empty_str_p,
                                                   arg1,
                                                   false);
-  JERRY_ASSERT (ecma_is_value_true (put_comp_val));
+  if (!ecma_is_value_true (put_comp_val))
+  {
+    ecma_deref_object (obj_wrapper_p);
```
Comment (akosthekiss) [inline jerry-core/ecma/builtin-objects/ecma-builtin-json.c]: Is this enough? Some lines below, the normal code path frees `put_comp_val`, `empty_str_p`, and `obj_wrapper_p` before returning. I think the error handling code path should also do proper cleanup. Perhaps
```c
if (ecma_is_value_true (put_comp_val))
{
  ECMA_TRY_CATCH (str_val,
                  ecma_builtin_json_str (empty_str_p, obj_wrapper_p, &context),
                  ret_value);
  ret_value = ecma_copy_value (str_val);
  ECMA_FINALIZE (str_val);
}
else
{
  ret_value = ECMA_VALUE_UNDEFINED;
}
```
might work better.

Note: the normal code path mysteriously frees `put_comp_val ` twice. That could be fixed now, I think.

**Comment by pmarkee** [comment]
Thanks for the review @akosthekiss , I have updated accordingly.

File: jerry-core/ecma/builtin-objects/ecma-builtin-json.c [hunk 3]
```diff
@@ -923,13 +923,20 @@ static ecma_value_t ecma_builtin_json_str_helper (const ecma_value_t arg1, /**<
...
-  ecma_free_value (put_comp_val);
-  ECMA_TRY_CATCH (str_val,
-                  ecma_builtin_json_str (empty_str_p, obj_wrapper_p, &context),
-                  ret_value);
-  ret_value = ecma_copy_value (str_val);
-  ECMA_FINALIZE (str_val);
+
+  if (ecma_is_value_true (put_comp_val))
+  {
+    ECMA_TRY_CATCH (str_val,
```
Comment (LaszloLango) [inline jerry-core/ecma/builtin-objects/ecma-builtin-json.c]: This can be simplified. `ECMA_TRY_CATCH` is unnecessary, the following code is equal:
```
{
  ret_value = ecma_builtin_json_str (empty_str_p, obj_wrapper_p, &context);
}
```

Comment (LaszloLango) [reply jerry-core/ecma/builtin-objects/ecma-builtin-json.c]: `ecma_copy_value` was needed because of the `ECMA_FINALIZE`. Without the `ECMA_TRY_CATCH` and `ECMA_FINALIZE` it is not needed anymore.

Comment (akosthekiss) [reply jerry-core/ecma/builtin-objects/ecma-builtin-json.c]: Indeed. That makes everything a lot simpler.

**Comment by pmarkee** [comment]
Thanks @LaszloLango , I have updated the PR.
