### PR TITLE
Mark target_function of bound objects.

### LINKED ISSUE #1621: Assertion 'ecma_op_is_callable (ecma_make_object_value (func_obj_p))' failed in ecma_op_function_call
###### Jerry version:

```
Checked revision: 3de72af
Build: debug.linux
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript

var eval = eval.bind()
eval(Math.cos())
```

###### Build command:

```
./tools/build.py --clean --debug --compile-flag=-m32 --system-allocator=on --jerry-libc=off
```

###### Backtrace:

```
ICE: Assertion 'ecma_op_is_callable (ecma_make_object_value (func_obj_p))' failed at jerryscript/jerry-core/ecma/operations/ecma-function-object.c(ecma_op_function_call):453.
Error: ERR_FAILED_INTERNAL_ASSERTION
bt
#0  0xf7ffdbe9 in __kernel_vsyscall ()
#1  0x080f2337 in raise ()
#2  0x080b9e77 in abort ()
#3  0x0805776a in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/targets/default/jerry-port-default-fatal.c:53
#4  0x080707a3 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:61
#5  0x080707d6 in jerry_assert_fail (assertion=0x813a1b8 "ecma_op_is_callable (ecma_make_object_value (func_obj_p))", file=0x813a018 "jerryscript/jerry-core/ecma/operations/ecma-function-object.c", function=0x812c7dc <__func__.4225.lto_priv.421> "ecma_op_function_call", line=453) at jerryscript/jerry-core/jrt/jrt-fatals.c:85
#6  0x0807c3b0 in ecma_op_function_call (func_obj_p=0x837e938, this_arg_value=137882721, arguments_list_p=0xffffc058, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:453
#7  0x0807c74b in ecma_op_function_call (func_obj_p=0x837ec40, this_arg_value=72, arguments_list_p=0xffffc058, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:590
#8  0x0806280d in opfunc_call.lto_priv.245 (frame_ctx_p=0xffffc084) at jerryscript/jerry-core/vm/vm.c:385
#9  0x0805ae19 in vm_execute (frame_ctx_p=0xffffc084, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2651
#10 0x0805afd4 in vm_run (bytecode_header_p=0x837ea80, this_binding_value=137881147, lex_env_p=0x837e6e8, is_eval_code=false, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:2730
#11 0x080624a3 in vm_run_global (bytecode_p=0x837ea80) at jerryscript/jerry-core/vm/vm.c:211
#12 0x080b23c8 in jerry_run (func_val=137881883) at jerryscript/jerry-core/jerry.c:385
#13 0x080b1d50 in main (argc=3, argv=0xffffc4d4) at jerryscript/jerry-main/main-unix.c:726
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/)</sup>

### PR DESCRIPTION
**Pull request by zherczeg**
Fixes #1621.

### CODE REVIEW

File: jerry-main/main-unix.c [hunk 1]
```diff
@@ -627,6 +640,21 @@ main (int argc,
...
+  jerry_release_value (gc_func_name_val);
+  jerry_release_value (gc_value);
+
+  if (jerry_value_has_error_flag (ret_value))
+  {
+    jerry_port_log (JERRY_LOG_LEVEL_WARNING, "Warning: failed to register '__gc' method.");
+    print_unhandled_exception (ret_value);
+  }
+
+  jerry_release_value (ret_value);
```
Comment (akosthekiss) [inline jerry-main/main-unix.c]: The registration of an external function should be factored out into a helper function. The steps are always the same: create the function, create the string for its name, register it in the global object, handle failure, release everything.

File: jerry-main/main-unix.c [hunk 2]
```diff
@@ -107,6 +107,21 @@ assert_handler (const jerry_value_t func_obj_val __attribute__((unused)), /**< f
   }
 } /* assert_handler */
 
+/**
+ * Provide the '__gc' implementation for the engine.
```
Comment (akosthekiss) [inline jerry-main/main-unix.c]: _the_ '__gc' implementation? Is it mandated somewhere? Or is it introduced into the system for the sake of the fixed issue? Will it be useful elsewhere, too? Do other engines also expose their gc? If yes, also under this name?

Comment (zherczeg) [inline jerry-main/main-unix.c]: This is not the first time I needed a gc call, and I finally decided to create one. I chose `__gc()` because `gc()` is too short and might be defined by some tests. We don't need to follow other engines since this is our test utility.

Comment (akosthekiss) [inline jerry-main/main-unix.c]: Just a remark: after a quick search, I haven't found the `gc` string in any of the JS tests in tests/benchmarks,debugger,jerry,jerry-test-suite. Those double underscores prefix are quite unusual, at least to me (because none of our extensions - `assert` or `print` - to the standard-mandated environment use it).

And of course we don't _have_ to follow any other engines but it is worth taking a look around for best practices.

Comment (zherczeg) [inline jerry-main/main-unix.c]: Double underscore means system function. Print and assert are user functions. I saw other engines use engine_name.gc(), but they provide this as core part of the engine not in a utility application. I can change it to `gc` but that is too short for me.

File: jerry-main/main-unix.c [hunk 3]
```diff
@@ -334,6 +349,32 @@ print_unhandled_exception (jerry_value_t error_value) /**< error value */
...
+  jerry_release_value (function_name_val);
+
+  if (jerry_value_has_error_flag (result_val))
+  {
+    jerry_port_log (JERRY_LOG_LEVEL_WARNING, "Warning: failed to register '%s' method.", name_p);
+    print_unhandled_exception (result_val);
+  }
+
+  jerry_release_value (result_val);
+  jerry_release_value (global_obj_val);
```
Comment (akosthekiss) [inline jerry-main/main-unix.c]: Is there a reason why the values are released in this order and in these two phases? If "release everything as soon as possible" is the policy, then reference to the global object can be released after the `jerry_set_property` call. If "release everything as the last step, in reverse order of allocation", then  `result_val`, `function_name_val`, `function_val`, `global_obj_val` should be the order of release at the end of the function.

File: jerry-main/main-unix.c (hunk 2 above)
Comment (akosthekiss) [inline jerry-main/main-unix.c]: To me, (double) underscore prefix is arbitrary as I haven't seen it in use anywhere else in the code base (not referring to `assert` or `print` only). I'll vote for `gc()`, but let others speak their mind, too.

Comment (akosthekiss) [inline jerry-main/main-unix.c]: Note: I've just discovered that the mbedos5 port already has `gc()` in the global object with exactly the same implementation as proposed here.

**Comment by zherczeg** [comment]
I really don't like the gc() name but let it be.
