### PR TITLE
Fix heap buffer overflow in re_parse_char_class

### LINKED ISSUE #2230: heap-buffer-overflow in lit_read_code_unit_from_hex
((new RegExp("[\\u0")).exec("u"));

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

build command:
python ./tools/build.py --clean --debug --compile-flag=-fsanitize=address --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer --compile-flag=-fno-common --jerry-libc=off --static-link=off --lto=off --error-message=on --system-allocator=on

=================================================================
==9567==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf580075c at pc 0x080f9f5a bp 0xffdf2a48 sp 0xffdf2a38
READ of size 1 at 0xf580075c thread T0
    #0 0x80f9f59 in lit_read_code_unit_from_hex /home/b/jerryscript/jerry-core/lit/lit-char-helpers.c:443
    #1 0x811df42 in re_parse_char_class /home/b/jerryscript/jerry-core/parser/regexp/re-parser.c:431
    #2 0x811a7b5 in re_parse_alternative /home/b/jerryscript/jerry-core/parser/regexp/re-compiler.c:399
    #3 0x811b5f7 in re_compile_bytecode /home/b/jerryscript/jerry-core/parser/regexp/re-compiler.c:564
    #4 0x80e2057 in ecma_op_create_regexp_object /home/b/jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:292
    #5 0x80bf83b in ecma_builtin_regexp_dispatch_construct /home/b/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp.c:136
    #6 0x80a0e9d in ecma_builtin_dispatch_construct /home/b/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:154
    #7 0x81358b3 in opfunc_construct /home/b/jerryscript/jerry-core/vm/vm.c:475
    #8 0x81358b3 in vm_execute /home/b/jerryscript/jerry-core/vm/vm.c:2849
    #9 0x8137a0d in vm_run /home/b/jerryscript/jerry-core/vm/vm.c:2924
    #10 0x8137a0d in vm_run_global /home/b/jerryscript/jerry-core/vm/vm.c:224
    #11 0x8057509 in jerry_run /home/b/jerryscript/jerry-core/api/jerry.c:562
    #12 0x804c176 in main /home/b/jerryscript/jerry-main/main-unix.c:611
    #13 0xf7005636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #14 0x804f8e9  (/home/b/jerryscript/build/bin/jerry+0x804f8e9)

0xf580075c is located 0 bytes to the right of 12-byte region [0xf5800750,0xf580075c)
allocated by thread T0 here:
    #0 0xf7239dee in malloc (/usr/lib32/libasan.so.2+0x96dee)
    #1 0x804f544 in jmem_heap_alloc_block_internal /home/b/jerryscript/jerry-core/jmem/jmem-heap.c:324
    #2 0x804f544 in jmem_heap_gc_and_alloc_block /home/b/jerryscript/jerry-core/jmem/jmem-heap.c:360
    #3 0x804f544 in jmem_heap_alloc_block /home/b/jerryscript/jerry-core/jmem/jmem-heap.c:406
    #4 0x80650aa in ecma_new_ecma_string_from_utf8 /home/b/jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:232
    #5 0x807d593 in ecma_find_or_create_literal_string /home/b/jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:73
    #6 0x810487a in parser_compute_indicies /home/b/jerryscript/jerry-core/parser/js/js-parser.c:201
    #7 0x810487a in parser_post_processing /home/b/jerryscript/jerry-core/parser/js/js-parser.c:1441
    #8 0x8110f8a in parser_parse_source /home/b/jerryscript/jerry-core/parser/js/js-parser.c:2267
    #9 0x8112c78 in parser_parse_script /home/b/jerryscript/jerry-core/parser/js/js-parser.c:2764
    #10 0x8056f72 in jerry_parse /home/b/jerryscript/jerry-core/api/jerry.c:388
    #11 0x8056f72 in jerry_parse_named_resource /home/b/jerryscript/jerry-core/api/jerry.c:446
    #12 0x804c140 in main /home/b/jerryscript/jerry-main/main-unix.c:602
    #13 0xf7005636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/b/jerryscript/jerry-core/lit/lit-char-helpers.c:443 lit_read_code_unit_from_hex
Shadow bytes around the buggy address:
  0x3eb00090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb000a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb000b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb000c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb000d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x3eb000e0: fa fa 00 01 fa fa 00 00 fa fa 00[04]fa fa fd fa
  0x3eb000f0: fa fa 00 05 fa fa 00 02 fa fa 00 06 fa fa 00 00
  0x3eb00100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb00110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb00120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3eb00130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==9567==ABORTING

### LINKED ISSUE #2237: heap-buffer-overflow in lit_read_code_unit_from_utf8
(new RegExp("[\\u0020")).exec("u");

=================================================================
==30634==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf600075f at pc 0x080ff179 bp 0xffe3dc58 sp 0xffe3dc48
READ of size 1 at 0xf600075f thread T0
    #0 0x80ff178 in lit_read_code_unit_from_utf8 /home/b/jerryscript/jerry-core/lit/lit-strings.c:409
    #1 0x80ff178 in lit_utf8_peek_next /home/b/jerryscript/jerry-core/lit/lit-strings.c:500
    #2 0x811e0c0 in re_parse_char_class /home/b/jerryscript/jerry-core/parser/regexp/re-parser.c:437
    #3 0x811a7b5 in re_parse_alternative /home/b/jerryscript/jerry-core/parser/regexp/re-compiler.c:399
    #4 0x811b5f7 in re_compile_bytecode /home/b/jerryscript/jerry-core/parser/regexp/re-compiler.c:564
    #5 0x80e2057 in ecma_op_create_regexp_object /home/b/jerryscript/jerry-core/ecma/operations/ecma-regexp-object.c:292
    #6 0x80bf83b in ecma_builtin_regexp_dispatch_construct /home/b/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp.c:136
    #7 0x80a0e9d in ecma_builtin_dispatch_construct /home/b/jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.inc.h:154
    #8 0x81358b3 in opfunc_construct /home/b/jerryscript/jerry-core/vm/vm.c:475
    #9 0x81358b3 in vm_execute /home/b/jerryscript/jerry-core/vm/vm.c:2849
    #10 0x8137a0d in vm_run /home/b/jerryscript/jerry-core/vm/vm.c:2924
    #11 0x8137a0d in vm_run_global /home/b/jerryscript/jerry-core/vm/vm.c:224
    #12 0x8057509 in jerry_run /home/b/jerryscript/jerry-core/api/jerry.c:562
    #13 0x804c176 in main /home/b/jerryscript/jerry-main/main-unix.c:611
    #14 0xf77ea636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)
    #15 0x804f8e9  (/home/b/jerryscript/build/bin/jerry+0x804f8e9)

0xf600075f is located 0 bytes to the right of 15-byte region [0xf6000750,0xf600075f)
allocated by thread T0 here:
    #0 0xf7a1edee in malloc (/usr/lib32/libasan.so.2+0x96dee)
    #1 0x804f544 in jmem_heap_alloc_block_internal /home/b/jerryscript/jerry-core/jmem/jmem-heap.c:324
    #2 0x804f544 in jmem_heap_gc_and_alloc_block /home/b/jerryscript/jerry-core/jmem/jmem-heap.c:360
    #3 0x804f544 in jmem_heap_alloc_block /home/b/jerryscript/jerry-core/jmem/jmem-heap.c:406
    #4 0x80650aa in ecma_new_ecma_string_from_utf8 /home/b/jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:232
    #5 0x807d593 in ecma_find_or_create_literal_string /home/b/jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:73
    #6 0x810487a in parser_compute_indicies /home/b/jerryscript/jerry-core/parser/js/js-parser.c:201
    #7 0x810487a in parser_post_processing /home/b/jerryscript/jerry-core/parser/js/js-parser.c:1441
    #8 0x8110f8a in parser_parse_source /home/b/jerryscript/jerry-core/parser/js/js-parser.c:2267
    #9 0x8112c78 in parser_parse_script /home/b/jerryscript/jerry-core/parser/js/js-parser.c:2764
    #10 0x8056f72 in jerry_parse /home/b/jerryscript/jerry-core/api/jerry.c:388
    #11 0x8056f72 in jerry_parse_named_resource /home/b/jerryscript/jerry-core/api/jerry.c:446
    #12 0x804c140 in main /home/b/jerryscript/jerry-main/main-unix.c:602
    #13 0xf77ea636 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18636)

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/b/jerryscript/jerry-core/lit/lit-strings.c:409 lit_read_code_unit_from_utf8
Shadow bytes around the buggy address:
  0x3ec00090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec000d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x3ec000e0: fa fa 00 01 fa fa 00 00 fa fa 00[07]fa fa fd fa
  0x3ec000f0: fa fa 00 05 fa fa 00 02 fa fa 00 06 fa fa 00 00
  0x3ec00100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec00110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec00120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ec00130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==30634==ABORTING

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2230 and fixes #2237.
Test cases are added for both issues and also adds new cases which caused the same error.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/regexp/re-parser.c [hunk 1]
```diff
@@ -419,15 +419,17 @@ re_parse_char_class (re_parser_ctx_t *parser_ctx_p, /**< number of classes */
         }
 
         parser_ctx_p->input_curr_p += 2;
-        if (is_range == false && lit_utf8_peek_next (parser_ctx_p->input_curr_p) == LIT_CHAR_MINUS)
+        if (parser_ctx_p->input_curr_p < parser_ctx_p->input_end_p &&
+            is_range == false &&
+            lit_utf8_peek_next (parser_ctx_p->input_curr_p) == LIT_CHAR_MINUS)
```
Comment (akosthekiss) [inline jerry-core/parser/regexp/re-parser.c]: The formatting of this condition is out of style. It should be
```
if (cond1
    && cond2
    && cond3)
{
}
```

File: jerry-core/parser/regexp/re-parser.c [hunk 2]
```diff
@@ -437,7 +439,9 @@ re_parse_char_class (re_parser_ctx_t *parser_ctx_p, /**< number of classes */
         }
 
         parser_ctx_p->input_curr_p += 4;
-        if (is_range == false && lit_utf8_peek_next (parser_ctx_p->input_curr_p) == LIT_CHAR_MINUS)
+        if (parser_ctx_p->input_curr_p < parser_ctx_p->input_end_p &&
+            is_range == false &&
+            lit_utf8_peek_next (parser_ctx_p->input_curr_p) == LIT_CHAR_MINUS)
```
Comment (akosthekiss) [inline jerry-core/parser/regexp/re-parser.c]: same style issue

**Comment by rerobika** [comment]
@akosthekiss Thanks for the review, I've applied your suggestions.

File: tests/jerry/regression-test-issue-2230.js [hunk 3]
```diff
@@ -0,0 +1,26 @@
...
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+
+try {
+  ((new RegExp("[\\u0")).exec("u"));
+} catch (e) {
```
Comment (akosthekiss) [inline tests/jerry/regression-test-issue-2230.js]: One more note: is it expected that the regex exec throws an exception? In that case we should add an `assert (false)` after the regex and before the catch IMO. Otherwise the test could pass without checking any assertions.

(same note to all try-catches in both tests)

Comment (rerobika) [reply tests/jerry/regression-test-issue-2230.js]: Good catch! Also the PR is rebased to the latest master.
