### PR TITLE
Fix assignment lookahead in parser_process_group_expression

### LINKED ISSUE #3815: Assertion (flags >> CBC_STACK_ADJUST_SHIFT) >= CBC_STACK_ADJUST_BASE || (CBC_STACK_ADJUST_BASE - (flags >> CBC_STACK_ADJUST_SHIFT)) <= context_p->stack_depth in parser_flush_cbc
###### JerryScript revision
3b4c2592

###### Build platform
Linux-4.15.0-88-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset --stack-limit=32
```

###### Test case
```javascript
($( )) = $
```

###### Output
```text
ICE: Assertion '(flags >> CBC_STACK_ADJUST_SHIFT) >= CBC_STACK_ADJUST_BASE || (CBC_STACK_ADJUST_BASE - (flags >> CBC_STACK_ADJUST_SHIFT)) <= context_p->stack_depth' failed at jerryscript/jerry-core/parser/js/js-parser-util.c(parser_flush_cbc):181.
Error: ERR_FAILED_INTERNAL_ASSERTION
ASAN:DEADLYSIGNAL
=================================================================
==24536==ERROR: AddressSanitizer: ABRT on unknown address 0x00005fd8 (pc 0xf7fa9079 bp 0xffe9224c sp 0xffe92230 T0)
    #0 0xf7fa9078  (linux-gate.so.1+0x1078)
    #1 0xf7fa9078  (linux-gate.so.1+0x1078)
    #2 0xf77d0831 in raise (/lib/i386-linux-gnu/libc.so.6+0x2d831)
    #3 0xf77d1cc0 in abort (/lib/i386-linux-gnu/libc.so.6+0x2ecc0)
    #4 0x565f736b in jerry_port_fatal jerryscript/jerry-port/default/default-fatal.c:30
    #5 0x566aeb8d in jerry_fatal jerryscript/jerry-core/jrt/jrt-fatals.c:63
    #6 0x566aebce in jerry_assert_fail jerryscript/jerry-core/jrt/jrt-fatals.c:87
    #7 0x565eb716 in parser_flush_cbc jerryscript/jerry-core/parser/js/js-parser-util.c:180
    #8 0x56616295 in parser_parse_block_expression jerryscript/jerry-core/parser/js/js-parser-expr.c:3431
    #9 0x5662ad91 in parser_parse_statements jerryscript/jerry-core/parser/js/js-parser-statm.c:3154
    #10 0x566bdd2f in parser_parse_source jerryscript/jerry-core/parser/js/js-parser.c:2177
    #11 0x566c1b17 in parser_parse_script jerryscript/jerry-core/parser/js/js-parser.c:2808
    #12 0x5671570e in jerry_parse jerryscript/jerry-core/api/jerry.c:447
    #13 0x5671233e in main jerryscript/jerry-main/main-unix.c:750
    #14 0xf77bbe80 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18e80)
    #15 0x565ea1e0  (jerryscript/build_gcc_asan_es2015/bin/jerry+0x1a1e0)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: ABRT (linux-gate.so.1+0x1078) 
==24536==ABORTING
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator).</sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3815.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser-expr.c [hunk 1]
```diff
@@ -3398,19 +3398,21 @@ parser_process_group_expression (parser_context_t *context_p, /**< context */
   parser_stack_pop_uint8 (context_p);
   lexer_next_token (context_p);
 
-  if (context_p->token.type == LEXER_ASSIGN)
+#if ENABLED (JERRY_ES2015)
+  if (context_p->token.type == LEXER_ASSIGN
+      && parser_is_assignment_expr (context_p))
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-expr.c:3403]: What about limiting this to identifiers?

Comment (rerobika) [reply jerry-core/parser/js/js-parser-expr.c:3403]: Good idea.

File: jerry-core/parser/js/js-parser-expr.c [hunk 2]
```diff
@@ -3398,21 +3393,17 @@ parser_process_group_expression (parser_context_t *context_p, /**< context */
...
 #if ENABLED (JERRY_ES2015)
-    if (JERRY_UNLIKELY (token == LEXER_LEFT_PAREN))
-    {
-      flags = PARSER_PATTERN_GROUP_EXPR;
-    }
-#endif /* ENABLED (JERRY_ES2015) */
-    parser_append_binary_single_assignment_token (context_p, flags);
-    lexer_next_token (context_p);
-    return true;
+  /* Lookahead for anonymous function declatartion after '=' token when the assignment base is LHS expression
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-expr.c:3397]: declatartion -> declaration
