### PR TITLE
Fix #1947

### LINKED ISSUE #1947: Assertion failed in jmem_heap_finalize
###### Jerry version:

```
Checked revision: 6fe4d06
Build command: ./tools/build.py --clean --debug --profile=es2015-subset --compile-flag=-m32 --system-allocator=on --jerry-libc=off --error-messages=on
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
function $ ( ) { function $ ( ) { switch ( $ ? $ : \u018E ) {} } }
```

###### Backtrace:

```
ICE: Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed at jerryscript//jerry-core/jmem/jmem-heap.c(jmem_heap_finalize):184.
Error: ERR_FAILED_INTERNAL_ASSERTION

```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/) with [Grammarinator](https://github.com/renatahodovan/grammarinator)</sup>

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
If a literal was assigned the unused flag it wasn't freed, however it could have been not empty, therefore should've been freed.

JerryScript-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

**Comment by DanielBallaSZTE** [comment]
@zherczeg I have added the testcase, thanks for the review.

File: tests/jerry/regression-test-issue-1947.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+//
+// Unless required by applicable law or agreed to in writing, software
+// distributed under the License is distributed on an "AS IS" BASIS
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+function a () {
+ function b () {
+  \u018E
```
Comment (zherczeg) [inline tests/jerry/regression-test-issue-1947.js]: \u0041 (letter `A` I think) is enough

**Comment by DanielBallaSZTE** [comment]
@zherczeg I've updated the testcase, and added a comment to it.

**Comment by yichoi** [comment]
LGTM
