### PR TITLE
Local functions should not be created globally.

### LINKED ISSUE #3286: Assertion property_p == NULL || !(*property_p & ECMA_PROPERTY_FLAG_ENUMERABLE) in vm_init_loop
###### JerryScript revision
859954b3

###### Build platform
Linux-4.15.0-62-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
let b
( undefined )
{
  {
    print ( )
  }
  {
    eval ( 'function b() {};' )
  }
  print ( )
}
```

###### Output
```text
ICE: Assertion 'property_p == NULL || !(*property_p & ECMA_PROPERTY_FLAG_ENUMERABLE)' failed at jerryscript/jerry-core/vm/vm.c(vm_init_loop):926.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657a63c in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x565fe7f1 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x565fe832 in jerry_assert_fail (assertion=0x566be360 "property_p == NULL || !(*property_p & ECMA_PROPERTY_FLAG_ENUMERABLE)", file=0x566bdf00 "jerryscript/jerry-core/vm/vm.c", function=0x5669e9e0 <__func__.6176.lto_priv.445> "vm_init_loop", line=926) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x565da9a7 in vm_init_loop (frame_ctx_p=0xffffbf80) at jerryscript/jerry-core/vm/vm.c:926
#7  0x565e677b in vm_loop (frame_ctx_p=0xffffbf80) at jerryscript/jerry-core/vm/vm.c:2968
#8  0x565ebaa2 in vm_execute (frame_ctx_p=0xffffbf80, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3727
#9  0x565ec444 in vm_run (bytecode_header_p=0xf5300d90, this_binding_value=4126149459, lex_env_p=0xf5d005d0, parse_opts=66, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3855
#10 0x565d867c in vm_run_eval (bytecode_data_p=0xf5300d90, parse_opts=66) at jerryscript/jerry-core/vm/vm.c:347
#11 0x56629017 in ecma_op_eval_chars_buffer (code_p=0xf5f0088c "function b() {};", code_buffer_size=16, parse_opts=66) at jerryscript/jerry-core/ecma/operations/ecma-eval.c:116
#12 0x56628cda in ecma_op_eval (code_p=0xf5f00880, parse_opts=2) at jerryscript/jerry-core/ecma/operations/ecma-eval.c:58
#13 0x565bae5e in ecma_builtin_global_object_eval (x=4126148737) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.c:111
#14 0x565be623 in ecma_builtin_global_dispatch_routine (builtin_routine_id=74, this_arg=72, arguments_list_p=0xffffc3f0, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-global.c:1164
#15 0x56659a72 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_GLOBAL, builtin_routine_id=74, this_arg_value=72, arguments_list_p=0xffffc3f0, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1020
#16 0x56659cd3 in ecma_builtin_dispatch_call (obj_p=0xf5f00730, this_arg_value=72, arguments_list_p=0xffffc684, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1045
#17 0x5662b371 in ecma_op_function_call (func_obj_p=0xf5f00730, this_arg_value=72, arguments_list_p=0xffffc684, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:773
#18 0x565d921e in opfunc_call (frame_ctx_p=0xffffc6f0) at jerryscript/jerry-core/vm/vm.c:583
#19 0x565ebb02 in vm_execute (frame_ctx_p=0xffffc6f0, arg_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3733
#20 0x565ec444 in vm_run (bytecode_header_p=0xf5b03880, this_binding_value=4126149459, lex_env_p=0xf5d007b0, parse_opts=0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:3855
#21 0x565d84a6 in vm_run_global (bytecode_p=0xf5b03880) at jerryscript/jerry-core/vm/vm.c:283
#22 0x5666fa22 in jerry_run (func_val=4126148691) at jerryscript/jerry-core/api/jerry.c:595
#23 0x5666c198 in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:740
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by zherczeg**
Fixes #3286.

Note: I don't want to add the original test case because it prints newlines to the screen. Also my test has assertions as well.

### CODE REVIEW

File: tests/jerry/es2015/let11.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+let b = 5;
+eval ( 'function b() { return 8; }; assert(b() === 8);' );
+assert(b === 5);
```
Comment (galpeter) [inline tests/jerry/es2015/let11.js]: So.. do we have a space before parenthesis or nor (and also after it)?
