### PR TITLE
Fix parsing of UTF-8 RegExp literals

### LINKED ISSUE #1831: Assertion 'lit_is_valid_cesu8_string (string_p, string_size)' failed in ecma_new_ecma_string_from_utf8
###### Jerry version:

```
Checked revision: 31cd3b8
Build command: ./tools/build.py --clean --debug --error-messages=on
```
###### OS:

```
Ubuntu 16.04.2 LTS
```
###### Test case:

```javascript
/኱𞻲/‌ஃ︠﹍
```

The [test](https://github.com/jerryscript-project/jerryscript/files/1008577/test.txt) file is attached (saved as txt to be accepted by GH).

###### Backtrace:

```
ICE: Assertion 'lit_is_valid_cesu8_string (string_p, string_size)' failed at jerryscript/jerry-core/ecma/base/ecma-helpers-string.c(ecma_new_ecma_string_from_utf8):154.
Error: ERR_FAILED_INTERNAL_ASSERTION
bt
#0  0xf7fd8be9 in __kernel_vsyscall ()
#1  0xf7898ea9 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf789a407 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x08055111 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x0809cbab in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x0809cbde in jerry_assert_fail (assertion=0x8157a40 "lit_is_valid_cesu8_string (string_p, string_size)", file=0x81578c0 "jerryscript/jerry-core/ecma/base/ecma-helpers-string.c", function=0x811dfe0 <__func__.3102.lto_priv.698> "ecma_new_ecma_string_from_utf8", line=154) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x080f977a in ecma_new_ecma_string_from_utf8 (string_p=0x8180ba1 <buffer.lto_priv+1> "\341\212\261\360\236\273\262/‌ஃ︠﹍", string_size=7) at jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:154
#7  0x08086074 in lexer_construct_regexp_object (context_p=0xffffbe90, parse_only=false) at jerryscript/jerry-core/parser/js/js-lexer.c:1819
#8  0x08062417 in parser_parse_unary_expression.lto_priv.192 (context_p=0xffffbe90, grouping_level_p=0xffffbbf0) at jerryscript/jerry-core/parser/js/js-parser-expr.c:647
#9  0x080522c4 in parser_parse_expression (context_p=0xffffbe90, options=2) at jerryscript/jerry-core/parser/js/js-parser-expr.c:1363
#10 0x08079499 in parser_parse_statements (context_p=0xffffbe90) at jerryscript/jerry-core/parser/js/js-parser-statm.c:1981
#11 0x0809185d in parser_parse_source (source_p=0x8180ba0 <buffer.lto_priv> "/\341\212\261\360\236\273\262/‌ஃ︠﹍", size=21, strict_mode=0, error_location_p=0xffffc060) at jerryscript/jerry-core/parser/js/js-parser.c:2042
#12 0x08093b72 in parser_parse_script (source_p=0x8180ba0 <buffer.lto_priv> "/\341\212\261\360\236\273\262/‌ஃ︠﹍", size=21, is_strict=false, bytecode_data_p=0xffffc110) at jerryscript/jerry-core/parser/js/js-parser.c:2496
#13 0x08112233 in jerry_parse (source_p=0x8180ba0 <buffer.lto_priv> "/\341\212\261\360\236\273\262/‌ஃ︠﹍", source_size=21, is_strict=false) at jerryscript/jerry-core/api/jerry.c:312
#14 0x08112381 in jerry_parse_named_resource (name_p=0xffffc68a "/home/reni/data/.fuzzinator/jerry/test-17407-140390459994520.js", name_length=63, source_p=0x8180ba0 <buffer.lto_priv> "/\341\212\261\360\236\273\262/‌ஃ︠﹍", source_size=21, is_strict=false) at jerryscript/jerry-core/api/jerry.c:367
#15 0x08119373 in main (argc=3, argv=0xffffc3d4) at jerryscript/jerry-main/main-unix.c:664
```

<sup>Found by  [Fuzzinator](http://fuzzinator.readthedocs.io/) with [Grammarinator](https://github.com/renatahodovan/grammarinator)</sup>

### PR DESCRIPTION
**Pull request by LaszloLango**
Fixes #1831

JerryScript-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

File: jerry-core/ecma/base/ecma-helpers-string.c [hunk 1]
```diff
@@ -151,7 +151,11 @@ ecma_new_ecma_string_from_utf8 (const lit_utf8_byte_t *string_p, /**< utf-8 stri
                                 lit_utf8_size_t string_size) /**< string size */
 {
   JERRY_ASSERT (string_p != NULL || string_size == 0);
-  JERRY_ASSERT (lit_is_valid_cesu8_string (string_p, string_size));
+  if (!lit_is_valid_cesu8_string (string_p, string_size))
```
Comment (zherczeg) [inline jerry-core/ecma/base/ecma-helpers-string.c]: Isn't this function is only for cesu-8? (Name just legacy)

Comment (LaszloLango) [inline jerry-core/ecma/base/ecma-helpers-string.c]: I'm not sure this is right fix for this issue. IMHO this is the safest way. Should we fix this in `lexer_construct_regexp_object` instead?

Comment (zherczeg) [inline jerry-core/ecma/base/ecma-helpers-string.c]: We need to understand the problem. The assert says this function can only be called with a cesu-8 string. What is exactly happening here?

Comment (LaszloLango) [inline jerry-core/ecma/base/ecma-helpers-string.c]: The input source (file) is in a valid utf8 format but not in cesu8 format, so `lexer_construct_regexp_object` calls the `ecma_new_ecma_string_from_utf8` with an utf8 string and the assert fails. I have concerns, because this might happen a lot of places where `ecma_new_ecma_string_from_utf8` is called. For example what happens if such strings appears in a variable name or string literals, etc.

Comment (zherczeg) [inline jerry-core/ecma/base/ecma-helpers-string.c]: It shouldn't happen in many places. I suspect in this case the function is directly called by the lexer. For other strings the lexer converts them to cesu-8, but it does not touch regexes because they are special. So please check the backtrace.

Comment (LaszloLango) [inline jerry-core/ecma/base/ecma-helpers-string.c]: > For other strings the lexer converts them to cesu-8
I didn't know that. In that case it is better to fix this in `lexer_construct_regexp_object`. I'll update the PR.

File: jerry-core/parser/js/js-lexer.c [hunk 2]
```diff
@@ -1821,7 +1821,19 @@ lexer_construct_regexp_object (parser_context_t *context_p, /**< context */
   const re_compiled_code_t *re_bytecode_p = NULL;
   ecma_value_t completion_value;
 
-  ecma_string_t *pattern_str_p = ecma_new_ecma_string_from_utf8 (regex_start_p, length);
+  ecma_string_t *pattern_str_p = NULL;
+
+  if (lit_is_valid_cesu8_string (regex_start_p, length))
+  {
+    pattern_str_p = ecma_new_ecma_string_from_utf8 (regex_start_p, length);
```
Comment (dbatyai) [inline jerry-core/parser/js/js-lexer.c]: Just an unrelated side-note: this function name is still incredibly misleading.
