### PR TITLE
Fix heap buffer overflow in lit_utf_incr

### LINKED ISSUE #2344: heap-buffer-overflow in lit_utf8_incr
###### Jerry version:

```
Checked revision: 872825fb
Build command: ./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
        --compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
        --compile-flag=-fno-common --compile-flag=-g --jerry-libc=off \
        --static-link=off --strip=off --system-allocator=on \
        --linker-flag=-fuse-ld=gold --error-messages=on
```
###### OS:

```
Ubuntu 17.10
```
###### Test case:

```javascript
new RegExp().compile("\\1\\");
```

###### Backtrace:

```
=================================================================
==7852==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xf5e0071b at pc 0x082020b9 bp 0xfff791a8 sp 0xfff7919c
READ of size 1 at 0xf5e0071b thread T0
    #0 0x82020b8 in lit_utf8_incr jerryscript/jerry-core/lit/lit-strings.c:529:59
    #1 0x821ff86 in re_count_num_of_groups jerryscript/jerry-core/parser/regexp/re-parser.c:265:9
    #2 0x821e2d6 in re_parse_next_token jerryscript/jerry-core/parser/regexp/re-parser.c:728:13
    #3 0x8217680 in re_parse_alternative jerryscript/jerry-core/parser/regexp/re-compiler.c:242:38
    #4 0x821647c in re_compile_bytecode jerryscript/jerry-core/parser/regexp/re-compiler.c:567:35
    #5 0x826791d in ecma_builtin_regexp_prototype_compile jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp-prototype.c:187:9
    #6 0x82667f4 in ecma_builtin_regexp_prototype_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-regexp-prototype.inc.h:55:1
    #7 0x81d16bf in ecma_builtin_dispatch_routine jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:897:10
    #8 0x81d144a in ecma_builtin_dispatch_call jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:922:17
    #9 0x81e0a8a in ecma_op_function_call jerryscript/jerry-core/ecma/operations/ecma-function-object.c:439:19
    #10 0x8235311 in opfunc_call jerryscript/jerry-core/vm/vm.c:442:24
    #11 0x8221a87 in vm_execute jerryscript/jerry-core/vm/vm.c:3003:7
    #12 0x8221068 in vm_run jerryscript/jerry-core/vm/vm.c:3087:10
    #13 0x822055e in vm_run_global jerryscript/jerry-core/vm/vm.c:225:28
    #14 0x817472c in jerry_run jerryscript/jerry-core/api/jerry.c:557:24
    #15 0x816e879 in main jerryscript/jerry-main/main-unix.c:660:21
    #16 0xf7ba4985 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18985)
    #17 0x80704a7 in _start (jerryscript/build/bin/_jerry+0x80704a7)

0xf5e0071b is located 0 bytes to the right of 11-byte region [0xf5e00710,0xf5e0071b)
allocated by thread T0 here:
    #0 0x8133ac4 in malloc (jerryscript/build/bin/_jerry+0x8133ac4)
    #1 0x81fb7a6 in jmem_heap_alloc_block_internal jerryscript/jerry-core/jmem/jmem-heap.c:342:10
    #2 0x81fb5e7 in jmem_heap_gc_and_alloc_block jerryscript/jerry-core/jmem/jmem-heap.c:378:24
    #3 0x81fb4c3 in jmem_heap_alloc_block jerryscript/jerry-core/jmem/jmem-heap.c:424:10
    #4 0x8236366 in ecma_alloc_string_buffer jerryscript/jerry-core/ecma/base/ecma-alloc.c:182:10
    #5 0x81a01d0 in ecma_new_ecma_string_from_utf8 jerryscript/jerry-core/ecma/base/ecma-helpers-string.c:224:21
    #6 0x81bca67 in ecma_find_or_create_literal_string jerryscript/jerry-core/ecma/base/ecma-literal-storage.c:73:29
    #7 0x8210395 in parser_compute_indicies jerryscript/jerry-core/parser/js/js-parser.c:201:30
    #8 0x8206517 in parser_post_processing jerryscript/jerry-core/parser/js/js-parser.c:1456:25
    #9 0x820e63c in parser_parse_source jerryscript/jerry-core/parser/js/js-parser.c:2340:21
    #10 0x820ce7b in parser_parse_script jerryscript/jerry-core/parser/js/js-parser.c:2837:22
    #11 0x81742fd in jerry_parse jerryscript/jerry-core/api/jerry.c:414:18
    #12 0x816e77f in main jerryscript/jerry-main/main-unix.c:651:19
    #13 0xf7ba4985 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18985)

SUMMARY: AddressSanitizer: heap-buffer-overflow jerryscript/jerry-core/lit/lit-strings.c:529:59 in lit_utf8_incr
Shadow bytes around the buggy address:
  0x3ebc0090: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ebc00a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ebc00b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ebc00c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ebc00d0: fa fa fa fa fa fa fd fa fa fa fd fa fa fa 00 00
=>0x3ebc00e0: fa fa 00[03]fa fa fd fa fa fa 00 05 fa fa 00 02
  0x3ebc00f0: fa fa 00 06 fa fa 00 00 fa fa fa fa fa fa fa fa
  0x3ebc0100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ebc0110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ebc0120: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x3ebc0130: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7852==ABORTING
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #2344.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

**Comment by rerobika** [comment]
Thank you for reminding me I've forgotten it.

File: jerry-core/parser/regexp/re-parser.c [hunk 1]
```diff
@@ -262,7 +262,10 @@ re_count_num_of_groups (re_parser_ctx_t *parser_ctx_p) /**< RegExp parser contex
     {
       case LIT_CHAR_BACKSLASH:
       {
-        lit_utf8_incr (&curr_p);
+        if (curr_p != parser_ctx_p->input_end_p)
```
Comment (akosthekiss) [inline jerry-core/parser/regexp/re-parser.c]: The LIT_CHAR_LEFT_PAREN case below uses < instead of !=. Is there a reason for a difference? < may be a bit safer than !=.

Comment (rerobika) [reply jerry-core/parser/regexp/re-parser.c]: There is no particular reason for using `!=` instead of `<` because both ways inflict the same behaviour.
I can change it if you like.

Comment (akosthekiss) [reply jerry-core/parser/regexp/re-parser.c]: If by any mistake curr_p jumps over input_end_p, < catches it but != does not. I'd suggest the change.

**Comment by rerobika** [comment]
@akosthekiss The PR is updated according to your suggestion! Thanks!
