### PR TITLE
Fix 'eval' checking in import/export statements.

### LINKED ISSUE #2975: Assertion JERRY_CONTEXT (jmem_heap_allocated_size) == 0 in jmem_heap_finalize
###### JerryScript revision
75728980

###### Build platform
Linux-4.15.0-54-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
var eval = eval.bind()
eval('import { c } from "tests/jerry/es2015/module-export-01.js";')
```

###### Output
```text
Script Error: SyntaxError: Unexported or circular import request.
ICE: Assertion 'JERRY_CONTEXT (jmem_heap_allocated_size) == 0' failed at jerryscript/jerry-core/jmem/jmem-heap.c(jmem_heap_finalize):143.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5059 in __kernel_vsyscall ()
#1  0xf77fd832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fecc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657a232 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:71
#4  0x5660bd75 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x5660bdb6 in jerry_assert_fail (assertion=0x566a53c0 "JERRY_CONTEXT (jmem_heap_allocated_size) == 0", file=0x566a5360 "jerryscript/jerry-core/jmem/jmem-heap.c", function=0x5667a500 <__func__.4561.lto_priv.505> "jmem_heap_finalize", line=143) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x5660b339 in jmem_heap_finalize () at jerryscript/jerry-core/jmem/jmem-heap.c:143
#7  0x5660af64 in jmem_finalize () at jerryscript/jerry-core/jmem/jmem-allocator.c:170
#8  0x56642abe in jerry_cleanup () at jerryscript/jerry-core/api/jerry.c:231
#9  0x566408cb in main (argc=3, argv=0xffffcc34) at jerryscript/jerry-main/main-unix.c:941
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by dbatyai**
Fixes #2975

JerryScript-DCO-1.0-Signed-off-by: Dániel Bátyai dbatyai@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser.c [hunk 1]
```diff
@@ -2396,6 +2396,11 @@ parser_parse_source (const uint8_t *arg_list_p, /**< function argument list */
   context.last_statement.current_p = NULL;
   context.status_flags |= parse_opts & PARSER_STRICT_MODE_MASK;
 
+  if (parse_opts & ECMA_PARSE_EVAL)
```
Comment (galpeter) [inline jerry-core/parser/js/js-parser.c]: AFAIK there should be a `ENABLED (JERRY_ES2015_MODULE_SYSTEM)` check around this.

File: tests/jerry/fail/regression-test-issue-2975.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
...
+ * Unless required by applicable law or agreed to in writing, software
+ * distributed under the License is distributed on an "AS IS" BASIS
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+/* Import/export statements must be in the global scope. */
+var eval = eval.bind();
+eval('import { c } from "tests/jerry/es2015/module-export-01.js";');
```
Comment (galpeter) [inline tests/jerry/fail/regression-test-issue-2975.js]: What kind of error should be returned here? Could we check it with `try-catch`?

File: jerry-core/parser/js/js-parser-module.c [hunk 3]
```diff
@@ -493,7 +493,7 @@ parser_module_check_request_place (parser_context_t *context_p) /**< parser cont
 {
   if (context_p->last_context_p != NULL
       || context_p->stack_top_uint8 != 0
-      || (JERRY_CONTEXT (status_flags) & ECMA_STATUS_DIRECT_EVAL) != 0
+      || (context_p->status_flags & PARSER_IS_EVAL) != 0
       || (context_p->status_flags & PARSER_IS_FUNCTION) != 0)
```
Comment (rerobika) [inline jerry-core/parser/js/js-parser-module.c]: I think these two lines can be merged into:
```
context_p->status_flags & (PARSER_IS_EVAL | PARSER_IS_FUNCTION) 
```
