### PR TITLE
Fix 'arguments' and 'caller' properties lazy listing in ES2015 profile

### LINKED ISSUE #3536: Assertion ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDACCESSOR || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VIRTUAL in ecma_is_property_configurable
###### JerryScript revision
b73100d9

###### Build platform
Linux-4.15.0-74-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript
class A {
    constructor() {
        var hasProp = $ => {}
        Object.preventExtensions(hasProp);
        Object.isSealed(hasProp);
    }
    super() {
        $: $
    }
}
class B extends A {
    constructor() {
        super() (super.super)
    }
}
new B
```

###### Output
```text
ICE: Assertion 'ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDACCESSOR || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VIRTUAL' failed at jerryscript/jerry-core/ecma/base/ecma-helpers.c(ecma_is_property_configurable):1128.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657d1e7 in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x56650566 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:63
#5  0x566505a7 in jerry_assert_fail (assertion=0x566fbf40 "ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDDATA || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_NAMEDACCESSOR || ECMA_PROPERTY_GET_TYPE (property) == ECMA_PROPERTY_TYPE_VI"..., file=0x566fad40 "jerryscript/jerry-core/ecma/base/ecma-helpers.c", function=0x566b8640 <__func__.5932.lto_priv.785> "ecma_is_property_configurable", line=1128) at jerryscript/jerry-core/jrt/jrt-fatals.c:87
#6  0x566876a5 in ecma_is_property_configurable (property=0 '\000') at jerryscript/jerry-core/ecma/base/ecma-helpers.c:1126
#7  0x565c9d6b in ecma_builtin_object_frozen_or_sealed_helper (obj_p=0xf5f004c0, mode=97) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-object.c:489
#8  0x565cb107 in ecma_builtin_object_dispatch_routine (builtin_routine_id=97, this_arg=4126147731, arguments_list_p=0xffffbf50, arguments_number=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtin-object.c:1060
#9  0x56698c23 in ecma_builtin_dispatch_routine (builtin_object_id=ECMA_BUILTIN_ID_OBJECT, builtin_routine_id=97, this_arg_value=4126147731, arguments_list_p=0xffffbf50, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1042
#10 0x56698e84 in ecma_builtin_dispatch_call (obj_p=0xf5f003a0, this_arg_value=4126147731, arguments_list_p=0xffffc244, arguments_list_len=1) at jerryscript/jerry-core/ecma/builtin-objects/ecma-builtins.c:1067
#11 0x5666bca6 in ecma_op_function_call_simple (func_obj_p=0xf5f003a0, this_arg_value=4126147731, arguments_list_p=0xffffc244, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:961
#12 0x5666c3c2 in ecma_op_function_call (func_obj_p=0xf5f003a0, this_arg_value=4126147731, arguments_list_p=0xffffc244, arguments_list_len=1) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1148
#13 0x5663413a in opfunc_call.lto_priv.482 (frame_ctx_p=0xffffc200) at jerryscript/jerry-core/vm/vm.c:702
#14 0x565e8011 in vm_execute (frame_ctx_p=0xffffc200) at jerryscript/jerry-core/vm/vm.c:4171
#15 0x565e862d in vm_run (bytecode_header_p=0xf4f01ea0, this_binding_value=4124050707, lex_env_p=0xf5d00590, arg_list_p=0xffffc4a0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4294
#16 0x5666bfd2 in ecma_op_function_call_simple (func_obj_p=0xf5f00700, this_arg_value=4124050707, arguments_list_p=0xffffc4a0, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1050
#17 0x5666cfb1 in ecma_op_function_construct (func_obj_p=0xf5f00700, this_arg_value=4124050707, arguments_list_p=0xffffc4a1, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1470
#18 0x5663336e in vm_super_call.lto_priv.481 (frame_ctx_p=0xffffc470) at jerryscript/jerry-core/vm/vm.c:516
#19 0x565e8021 in vm_execute (frame_ctx_p=0xffffc470) at jerryscript/jerry-core/vm/vm.c:4177
#20 0x565e862d in vm_run (bytecode_header_p=0xf6103d40, this_binding_value=4124050707, lex_env_p=0xf5d004f0, arg_list_p=0xffffc6f8, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4294
#21 0x5666bfd2 in ecma_op_function_call_simple (func_obj_p=0xf5f005b0, this_arg_value=4124050707, arguments_list_p=0xffffc6f8, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1050
#22 0x5666cfb1 in ecma_op_function_construct (func_obj_p=0xf5f005b0, this_arg_value=4124050707, arguments_list_p=0xffffc6f9, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:1470
#23 0x566346d3 in opfunc_construct.lto_priv.479 (frame_ctx_p=0xffffc6c0) at jerryscript/jerry-core/vm/vm.c:787
#24 0x565e804f in vm_execute (frame_ctx_p=0xffffc6c0) at jerryscript/jerry-core/vm/vm.c:4192
#25 0x565e862d in vm_run (bytecode_header_p=0xf4d031d0, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4294
#26 0x566329ae in vm_run_global (bytecode_p=0xf4d031d0) at jerryscript/jerry-core/vm/vm.c:286
#27 0x566a1cdb in jerry_run (func_val=4126148499) at jerryscript/jerry-core/api/jerry.c:593
#28 0x5669e33c in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:750
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3536.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/ecma/operations/ecma-function-object.c [hunk 1]
```diff
@@ -1814,11 +1815,17 @@ ecma_op_function_list_lazy_property_names (ecma_object_t *object_p, /**< functio
 
     /* 'prototype' property is non-enumerable (ECMA-262 v5, 13.2.18) */
     ecma_collection_push_back (for_non_enumerable_p, ecma_make_magic_string_value (LIT_MAGIC_STRING_PROTOTYPE));
+
+#if ENABLED (JERRY_ES2015)
+    append_caller_and_arguments = !(bytecode_data_p->status_flags & CBC_CODE_FLAGS_STRICT_MODE);
+#else /* !ENABLED (JERRY_ES2015) */
+    append_caller_and_arguments = (bytecode_data_p->status_flags & CBC_CODE_FLAGS_STRICT_MODE);
```
Comment (zherczeg) [inline jerry-core/ecma/operations/ecma-function-object.c]: Can we define this here?

Comment (rerobika) [reply jerry-core/ecma/operations/ecma-function-object.c]: Indeed, I've updated the PR.
