### PR TITLE
Fix this property reference on assignment patterns

### LINKED ISSUE #3348: Assertion ecma_is_value_object (iterator) in ecma_op_iterator_next
###### JerryScript revision
62356796

###### Build platform
Linux-4.15.0-62-generic-x86_64-with-Ubuntu-18.04-bionic

###### Build steps
```
./tools/build.py --clean --debug --compile-flag=-fsanitize=address \
--compile-flag=-m32 --compile-flag=-fno-omit-frame-pointer \
--compile-flag=-fno-common --compile-flag=-g \
--strip=off --system-allocator=on --logging=on \
--linker-flag=-fuse-ld=gold --error-messages=on --profile=es2015-subset
```

###### Test case
```javascript											
[ $, this.$] = [ ]
```

###### Output
```text
ICE: Assertion 'ecma_is_value_object (iterator)' failed at jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c(ecma_op_iterator_next):245.
Error: ERR_FAILED_INTERNAL_ASSERTION
```

###### Backtrace
```text
bt
#0  0xf7fd5079 in __kernel_vsyscall ()
#1  0xf77fc832 in raise () from /lib/i386-linux-gnu/libc.so.6
#2  0xf77fdcc1 in abort () from /lib/i386-linux-gnu/libc.so.6
#3  0x5657b78e in jerry_port_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-port/default/default-fatal.c:30
#4  0x56607f14 in jerry_fatal (code=ERR_FAILED_INTERNAL_ASSERTION) at jerryscript/jerry-core/jrt/jrt-fatals.c:58
#5  0x56607f55 in jerry_assert_fail (assertion=0x566da7c0 "ecma_is_value_object (iterator)", file=0x566da5a0 "jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c", function=0x566a5f00 <__func__.6193.lto_priv.635> "ecma_op_iterator_next", line=245) at jerryscript/jerry-core/jrt/jrt-fatals.c:82
#6  0x5663ce47 in ecma_op_iterator_next (iterator=72, value=8) at jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c:245
#7  0x5663d0e3 in ecma_op_iterator_step (iterator=72) at jerryscript/jerry-core/ecma/operations/ecma-iterator-object.c:366
#8  0x565e35c8 in vm_loop (frame_ctx_p=0xffffc490) at jerryscript/jerry-core/vm/vm.c:1945
#9  0x565ef4d9 in vm_execute (frame_ctx_p=0xffffc490) at jerryscript/jerry-core/vm/vm.c:4043
#10 0x565efb6a in vm_run (bytecode_header_p=0xf4f019f0, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0xffffc710, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4168
#11 0x5663ac44 in ecma_op_function_call (func_obj_p=0xf5f04990, this_arg_value=72, arguments_list_p=0xffffc710, arguments_list_len=0) at jerryscript/jerry-core/ecma/operations/ecma-function-object.c:851
#12 0x565dc721 in opfunc_call (frame_ctx_p=0xffffc6e0) at jerryscript/jerry-core/vm/vm.c:699
#13 0x565ef547 in vm_execute (frame_ctx_p=0xffffc6e0) at jerryscript/jerry-core/vm/vm.c:4049
#14 0x565efb6a in vm_run (bytecode_header_p=0xf4703e40, this_binding_value=4126149459, lex_env_p=0xf5d007b0, arg_list_p=0x0, arg_list_len=0) at jerryscript/jerry-core/vm/vm.c:4168
#15 0x565db046 in vm_run_global (bytecode_p=0xf4703e40) at jerryscript/jerry-core/vm/vm.c:286
#16 0x5667d3a6 in jerry_run (func_val=4126151187) at jerryscript/jerry-core/api/jerry.c:595
#17 0x56679b1c in main (argc=2, argv=0xffffcb24) at jerryscript/jerry-main/main-unix.c:740
```

<sup>Found by [Fuzzinator](http://fuzzinator.readthedocs.io/) with [grammarinator](https://github.com/renatahodovan/grammarinator). </sup>

### PR DESCRIPTION
**Pull request by rerobika**
This patch fixes #3348.

JerryScript-DCO-1.0-Signed-off-by: Robert Fancsik frobert@inf.u-szeged.hu

### CODE REVIEW

File: jerry-core/parser/js/js-parser-expr.c [hunk 1]
```diff
@@ -2434,6 +2434,13 @@ parser_pattern_process_assignment (parser_context_t *context_p, /**< context */
       {
         parser_raise_error (context_p, PARSER_ERR_INVALID_DESTRUCTURING_PATTERN);
       }
+      else if (context_p->last_cbc_opcode == CBC_PUSH_PROP_THIS_LITERAL)
```
Comment (zherczeg) [inline jerry-core/parser/js/js-parser-expr.c]: There is no need else here if I understand the code correctly.

Comment (rerobika) [reply jerry-core/parser/js/js-parser-expr.c]: Indeed, fixed.
